// ═══════════════════════════════════════════════════════════════════════════════
// BASIC x DAILY GUIDANCE LIBRARY — 81 combos
// Each entry: 8 do's + 8 avoids — knowledge-base accurate, short & actionable
// ═══════════════════════════════════════════════════════════════════════════════

export const BASIC_DAILY_GUIDANCE = {

  // ══ BASIC 1 (Sun) ══════════════════════════════════════════════════════════
  1: {
    1: {
      do: [
        "Send the important email you have been sitting on",
        "Step into a leadership role today — it fits",
        "Make the ask you have been postponing",
        "Be seen doing something that matters",
        "Make a public or professional announcement",
        "Follow through on a commitment others are watching",
        "Speak first in the meeting — your read is accurate",
        "Set the agenda, not just respond to others",
      ],
      avoid: [
        "Picking a fight just because you can win it",
        "Making decisions that affect others without consulting them",
        "Confusing confidence with arrogance today",
        "Announcing wins before they are complete",
        "Expecting others to match your pace today",
        "Dismissing feedback as irrelevant",
        "Making leadership moves that serve ego, not the goal",
        "Burning goodwill to prove a point",
      ],
    },
    2: {
      do: [
        "Call someone you have been meaning to reconnect with",
        "Listen more than you speak today",
        "Act on what your gut is telling you",
        "Be honest about what you need emotionally",
        "Check in on someone who has been quiet",
        "Do the creative work before the analytical work",
        "Express appreciation to someone who deserves it",
        "Let the conversation go somewhere unexpected",
      ],
      avoid: [
        "Making career decisions while emotionally activated",
        "Projecting strength when vulnerability would serve better",
        "Dismissing someone else's feeling as irrational",
        "Spending to manage an emotional problem",
        "Suppressing what is clearly asking to be expressed",
        "Using authority to shut down emotional honesty",
        "Pushing through a difficult feeling without acknowledging it",
        "Making financial decisions under emotional pressure",
      ],
    },
    3: {
      do: [
        "Ask advice from someone older or more experienced",
        "Make the decision that requires both courage and ethics",
        "Teach or explain something you know well",
        "Invest in something with long-term value today",
        "Mentor someone who is ready to receive it",
        "Read or study something that challenges your current thinking",
        "Share knowledge generously — it returns multiplied",
        "Make the ethical call even when the shortcut is tempting",
      ],
      avoid: [
        "Cutting moral corners to move faster",
        "Giving advice nobody asked for",
        "Expanding faster than your foundation supports",
        "Overconfidence disguised as vision",
        "Dismissing wisdom from an unexpected source",
        "Acting first and consulting the experienced person second",
        "Optimism that ignores what the numbers actually say",
        "Assuming your current level of knowledge is sufficient",
      ],
    },
    4: {
      do: [
        "Verify the information before you commit",
        "Generate options — do not lock in yet",
        "Ask the question that has been nagging you",
        "Research before any financial move today",
        "Read every line before signing anything",
        "Get a second opinion on the decision that feels certain",
        "Slow down the timeline if the other person is rushing you",
        "Document what was said — do not trust memory alone today",
      ],
      avoid: [
        "Signing or agreeing to anything without reading it",
        "Trusting a pitch that sounds too good to be true",
        "Making permanent decisions on incomplete data",
        "Moving fast because someone else is impatient",
        "Trusting first impressions as final assessments",
        "Committing money or time without independent verification",
        "Letting social pressure override your better judgment",
        "Assuming the opportunity will disappear if you pause to think",
      ],
    },
    5: {
      do: [
        "Close the deal you have been building toward",
        "Have the direct business conversation — no more circling",
        "Negotiate — your position is strong today",
        "Follow up on money that is owed to you",
        "Pitch to the person who has been considering you",
        "Make the financial decision you have fully analyzed",
        "Send the proposal or contract today",
        "Lock in terms before the energy shifts",
      ],
      avoid: [
        "Speed that misses the important detail",
        "Cold efficiency that damages relationships you will need",
        "Overconfidence in reading the other person",
        "Agreeing to something you have not fully costed",
        "Talking yourself out of a negotiation you were winning",
        "Letting perfect be the enemy of good enough to close",
        "Missing the human element in a commercial conversation",
        "Celebrating before the contract is signed",
      ],
    },
    6: {
      do: [
        "Appreciate someone who has been showing up for you",
        "Have the relationship conversation you have been avoiding",
        "Do something genuinely generous — not performative",
        "Invest in the connection that deserves it",
        "Create something that expresses care",
        "Show up warmly in a professional context — it opens doors",
        "Say the kind thing you have been thinking but not saying",
        "Invest in an experience over a possession today",
      ],
      avoid: [
        "Harsh words when frustrated — they stick today",
        "Using charm to avoid a real conversation",
        "Overcommitting to please people",
        "Neglecting your own needs while managing others",
        "Spending on comfort to avoid a difficult truth",
        "Prioritizing appearance over substance in a relationship",
        "Letting social grace substitute for competent action",
        "Making promises in a warm moment you cannot keep in a cold one",
      ],
    },
    7: {
      do: [
        "Trust what your instincts are saying about this person",
        "Let the outcome arrive without forcing it",
        "Make the intuitive call — logic already agrees with it",
        "Follow the pull that has no rational explanation",
        "Sit with a question without demanding an immediate answer",
        "Do the spiritual or reflective practice you have been skipping",
        "Trust the feeling that something has already resolved",
        "Let go of the thing that is done — stop managing it",
      ],
      avoid: [
        "Overanalyzing what your gut already knows",
        "Forcing a result that wants to come naturally",
        "Ignoring a feeling because it is inconvenient",
        "Pretending you do not know what you know",
        "Chasing recognition that is already coming",
        "Disrupting something that is moving in the right direction",
        "Filling silence that is doing useful work",
        "Letting analysis delay an action that is already correct",
      ],
    },
    8: {
      do: [
        "Do the hardest task on your list — start now",
        "Finish what was started before opening anything new",
        "Build the structure or system the long term needs",
        "Do the work that only you can do",
        "Honor a commitment that costs you something to keep",
        "Fix the recurring problem instead of working around it again",
        "Do the thing that compounds — not the thing that feels urgent",
        "Show up with full effort when no one is watching",
      ],
      avoid: [
        "Expecting recognition today — it comes through accumulated work",
        "Shortcuts on anything that carries your name",
        "Rushing the process Saturn has established",
        "Announcing effort instead of showing results",
        "Resenting the pace of genuine progress",
        "Abandoning a sound long-term plan for short-term relief",
        "Delegating what only you can do correctly",
        "Treating discipline as punishment instead of investment",
      ],
    },
    9: {
      do: [
        "Make the bold move — full energy and authority behind you",
        "Have the confrontation that has been overdue",
        "Start the physically demanding project today",
        "Put your name on something courageous",
        "Lead with decisiveness — hesitation costs more than boldness today",
        "Take the competitive action others are hesitating on",
        "Channel the aggression into output, not conflict",
        "Do the thing that requires nerve, not just intelligence",
      ],
      avoid: [
        "Starting fights that are not worth the cost",
        "Recklessness dressed as confidence",
        "Burning bridges in a moment of energy",
        "Ego-driven aggression when calm authority works better",
        "Impulse decisions that cannot be undone",
        "Letting the high energy bypass the necessary thinking",
        "Physical recklessness — the body is running hot today",
        "Picking the dramatic option when the quiet one works",
      ],
    },
  },

  // ══ BASIC 2 (Moon) ═════════════════════════════════════════════════════════
  2: {
    1: {
      do: [
        "Show up visibly today — be seen",
        "Make the public or professional move you have been hesitating on",
        "Lead with calm authority — people are watching",
        "Take credit for something you actually did",
        "Put your work in front of someone who can recognize it",
        "Speak clearly and directly in a professional setting",
        "Make the request that requires you to be visible",
        "Do the thing that moves you forward publicly",
      ],
      avoid: [
        "Suppressing emotion until it explodes later",
        "Over-explaining your reasoning to justify yourself",
        "Seeking approval before doing the right thing",
        "Comparing yourself to others today",
        "Letting insecurity drive a visibility decision",
        "Shrinking from a spotlight that is genuinely earned",
        "Making public moves from a reactive emotional place",
        "Confusing being seen with being understood",
      ],
    },
    2: {
      do: [
        "Do the creative work that has been calling you",
        "Have the emotionally honest conversation — it is time",
        "Connect deeply with one person today",
        "Write, create, or express something real",
        "Let yourself feel what is actually there without managing it",
        "Do the work that requires emotional intelligence, not just skill",
        "Rest without guilt if the body is asking for it",
        "Honor a commitment to yourself that keeps getting postponed",
      ],
      avoid: [
        "Isolating when you need people around you",
        "Emotional decisions made in private without consultation",
        "Ruminating on what cannot be changed today",
        "Using sensitivity as a reason to avoid necessary conflict",
        "Overcommitting emotionally to someone who is not reciprocating",
        "Confusing feeling deeply with knowing clearly",
        "Making financial decisions from an emotionally flooded state",
        "Numbing the feeling instead of moving through it",
      ],
    },
    3: {
      do: [
        "Spend time with family — it nourishes more than you expect",
        "Seek wisdom from someone you trust",
        "Plan something long-term with the people you love",
        "Have the meaningful conversation over a meal",
        "Share something you have learned with someone who will value it",
        "Give time and attention generously today",
        "Do the kind, generous thing without keeping score",
        "Invest in a relationship that has proven itself over time",
      ],
      avoid: [
        "Giving unsolicited advice to someone who has not asked",
        "Overextending emotionally for people who drain you",
        "Making financial decisions based on family pressure",
        "Ignoring your own needs while attending to others",
        "Letting emotional closeness override practical thinking",
        "Saying yes to something because you feel guilty saying no",
        "Assuming others need what you need right now",
        "Exhausting yourself trying to fix what is not yours to fix",
      ],
    },
    4: {
      do: [
        "Write your feelings down before acting on them",
        "Pause before responding to anything confusing today",
        "Ask one more question before you decide",
        "Trust the unease — do not dismiss it",
        "Postpone the commitment that does not feel ready",
        "Ground yourself physically before making any calls",
        "Seek clarity from someone outside the emotional situation",
        "Sleep on the decision that feels urgent",
      ],
      avoid: [
        "Major decisions made under emotional confusion",
        "Trusting someone too quickly when something feels off",
        "Signing or agreeing while feeling uncertain",
        "Buying something to relieve the anxiety",
        "Sending the emotional message before it has been reconsidered",
        "Confusing what feels true with what is true",
        "Acting on a Rahu-amplified impulse as if it were wisdom",
        "Letting confusion rush you into a commitment",
      ],
    },
    5: {
      do: [
        "Follow the intuitive business read — it is accurate today",
        "Make the financial decision you have been calculating",
        "Send the proposal or follow up on the money",
        "Act on the commercial opportunity in front of you",
        "Trust the number your gut gave before the spreadsheet",
        "Have the money conversation you have been avoiding",
        "Make the commercial connection that feels aligned",
        "Invest in something that serves both creativity and income",
      ],
      avoid: [
        "Emotional spending disguised as investment",
        "Mixing personal feelings into financial negotiations",
        "Overthinking a commercial decision that is already clear",
        "Letting someone else's urgency rush your timing",
        "Emotional generosity that creates financial strain",
        "Saying yes to the business relationship out of guilt",
        "Undervaluing what you offer because you feel uncertain today",
        "Waiting for perfect certainty before acting on a clear signal",
      ],
    },
    6: {
      do: [
        "Do something romantic or genuinely affectionate today",
        "Create something beautiful — your aesthetic sense is sharp",
        "Invest in a relationship that deserves real energy",
        "Cook, arrange, beautify — hands-on care today",
        "Express what you feel directly and warmly",
        "Do the creative work that has beauty as its goal",
        "Give someone your full, undistracted presence",
        "Do something that makes your environment feel more alive",
      ],
      avoid: [
        "Emotional overspending on experiences you cannot afford",
        "Using affection to avoid the real conversation",
        "Confusing comfort with connection",
        "Overcommitting to others while starving your own needs",
        "Romantic decisions made in the first flush of feeling",
        "Spending on beauty to manage an emotional problem",
        "Letting the desire for harmony prevent necessary honesty",
        "Mistaking intensity of feeling for depth of connection",
      ],
    },
    7: {
      do: [
        "Meditate, pray, or sit in silence for even ten minutes",
        "Trust what keeps surfacing in your mind",
        "Do the inner work you have been postponing",
        "Follow the subtle pull without needing to explain it",
        "Honor the sensitivity as a gift, not a problem",
        "Do the creative or spiritual work that requires stillness",
        "Let the answer form without forcing it",
        "Rest in a way that genuinely restores rather than distracts",
      ],
      avoid: [
        "Rationalizing what your intuition is already rejecting",
        "Numbing the sensitivity with distraction",
        "Second-guessing a clear inner signal",
        "Forcing logic onto something that is not logical",
        "Overstimulation on a day designed for depth",
        "Social obligations that drain without replenishing",
        "Performing wellness instead of actually resting",
        "Dismissing the feeling because it cannot be explained",
      ],
    },
    8: {
      do: [
        "Keep your daily structure even when it feels heavy",
        "Do one difficult thing before checking your phone",
        "Stay connected to at least one person today",
        "Be consistent even when no one is watching",
        "Do the routine task that keeps everything else working",
        "Show up for the commitment that feels inconvenient today",
        "Take the small action that maintains what matters",
        "Rest deliberately — not as avoidance, as strategy",
      ],
      avoid: [
        "Complete isolation — brief connection is medicine today",
        "Canceling commitments because you feel low",
        "Self-criticism that compounds the heaviness",
        "Substituting screens for real human contact",
        "Giving up on the routine because one day went badly",
        "Letting the emotional weight convince you nothing is working",
        "Making permanent decisions based on a temporary heaviness",
        "Collapsing the structure that has been holding things together",
      ],
    },
    9: {
      do: [
        "Channel the intensity into physical movement — go hard",
        "Write what you are feeling before you speak it",
        "Redirect competitive energy into creative output",
        "Pick one bold thing and give it everything",
        "Use the fire to complete something difficult",
        "Take physical action on a goal that has been waiting",
        "Express the intensity through art, sport, or building",
        "Do something that requires full physical presence",
      ],
      avoid: [
        "Arguments at home — emotional heat today leaves lasting marks",
        "Reactive messages or calls when angry",
        "Physical recklessness when the body is running hot",
        "Letting passion become aggression",
        "Emotional ultimatums made in the intensity of the moment",
        "Forcing a resolution to something that needs more time",
        "Spending the fire on conflict instead of creation",
        "Words in anger that undo months of relationship building",
      ],
    },
  },

  // ══ BASIC 3 (Jupiter) ══════════════════════════════════════════════════════
  3: {
    1: {
      do: [
        "Speak in a leadership context with full conviction",
        "Make the ethical decision even if it costs something",
        "Mentor or guide someone who needs direction",
        "Commit publicly to the principled position",
        "Lead by example in front of someone who is watching",
        "Make the decision that requires both authority and wisdom",
        "Teach something that challenges the people who need to grow",
        "Put your credibility behind the right thing",
      ],
      avoid: [
        "Moralizing without acting",
        "Leadership through lecture instead of example",
        "Overconfidence in your read of a complex situation",
        "Making promises in a strong moment you cannot keep in a weak one",
        "Authority without accountability",
        "Wisdom performed rather than practiced",
        "Taking credit for the team and criticism away from yourself",
        "Decisions that serve your status over your purpose",
      ],
    },
    2: {
      do: [
        "Connect with family over something meaningful",
        "Share your wisdom with someone who asked for it",
        "Do something creative that has real depth",
        "Be fully present with the people who matter",
        "Give the kind of care that requires sacrifice, not just intention",
        "Have the meaningful conversation you have been postponing",
        "Listen for what is not being said as much as what is",
        "Create something that expresses values, not just skill",
      ],
      avoid: [
        "Advice nobody asked for",
        "Emotional decisions dressed as wise choices",
        "Neglecting your own spiritual needs for others",
        "Overextending on behalf of people who will not reciprocate",
        "Using your knowledge to create distance rather than connection",
        "Generosity that depletes you past your genuine capacity",
        "Wisdom that separates instead of uniting",
        "Treating emotional honesty as less important than logical clarity",
      ],
    },
    3: {
      do: [
        "Study or read something that challenges you",
        "Teach what you know to someone who needs it",
        "Make the long-term investment in knowledge or skill",
        "Reflect seriously on a question that matters to you",
        "Seek out a perspective that directly contradicts yours",
        "Spend time with someone wiser than you",
        "Do the intellectual work that has compound value",
        "Practice the thing you believe in rather than just believing it",
      ],
      avoid: [
        "Spiritual arrogance — wisdom shared humbly lands, displayed does not",
        "Overconfidence in an area where you are still learning",
        "Expanding commitments beyond what can be honored",
        "Shortcuts in learning disguised as efficiency",
        "Certainty about things that are still unfolding",
        "Using knowledge to avoid the harder work of practice",
        "Treating your current understanding as the final understanding",
        "Wisdom without humility is just cleverness",
      ],
    },
    4: {
      do: [
        "Question your current assumptions before deciding",
        "Seek information from an unconventional source today",
        "Sit with the confusion — clarity is forming beneath it",
        "Write down what you actually know versus what you assume",
        "Consult someone whose judgment has been proven, not just impressive",
        "Slow down the process until clarity arrives on its own",
        "Separate the facts from the story you are telling about them",
        "Ask the experienced person the uncomfortable question",
      ],
      avoid: [
        "Following someone's guidance without verifying it",
        "Overcommitting based on optimistic projections",
        "Spiritual bypassing — using wisdom to avoid the hard thing",
        "Decisions made under social pressure today",
        "Confusing enthusiasm with accuracy",
        "Acting on inspiration before checking whether it is sound",
        "Trusting a charismatic certainty without your own discernment",
        "Large commitments based on incomplete information",
      ],
    },
    5: {
      do: [
        "Have the intelligent financial conversation you have been avoiding",
        "Make the strategic investment in education or skill",
        "Plan the next phase with both vision and detail",
        "Negotiate with both confidence and wisdom today",
        "Apply your knowledge directly to a financial decision",
        "Think long-term about a short-term financial pressure",
        "Make the investment that builds capability, not just assets",
        "Have the business conversation with the person who can actually decide",
      ],
      avoid: [
        "Speculation dressed as vision",
        "Optimistic financial projections without data",
        "Committing to financial timelines that require everything to go right",
        "Expanding before the current phase is stable",
        "Confusing intelligence about money with wisdom about it",
        "Financial generosity that creates personal scarcity",
        "Agreeing to terms without understanding them fully",
        "Using expertise to convince yourself of a bad decision",
      ],
    },
    6: {
      do: [
        "Do something genuinely beautiful for someone you love",
        "Give generously — time, attention, or something real",
        "Create something that expresses your values",
        "Invest in a relationship that deserves your full presence",
        "Share wisdom and warmth in equal measure today",
        "Do the generous thing without expecting recognition",
        "Invest in an experience that elevates both of you",
        "Express what you value about someone clearly",
      ],
      avoid: [
        "Overindulgence justified by good intentions",
        "Giving to avoid the harder conversation",
        "Aesthetic perfectionism that paralyzes action",
        "Spreading yourself too thin across too many relationships",
        "Generosity that enables rather than empowers",
        "Wisdom that tells others what to do instead of what you see",
        "Spending on beauty as a substitute for presence",
        "Using culture or taste as a way of creating separation",
      ],
    },
    7: {
      do: [
        "Spend time in real silence — not distracted quiet",
        "Follow the spiritual pull wherever it leads today",
        "Read something that challenges your current framework",
        "Trust the understanding that arrives without effort",
        "Do the inner practice without expecting visible results",
        "Ask the question that has no obvious answer",
        "Seek the wisdom that comes through experience, not just reading",
        "Give the mystery some room instead of filling it with explanation",
      ],
      avoid: [
        "Intellectual arrogance about spiritual knowledge",
        "Overthinking what practice is meant to quiet",
        "Withdrawing from life in the name of spiritual work",
        "Using wisdom as a shield against vulnerability",
        "Certainty about what cannot be known",
        "Spiritual experiences that require you to explain them constantly",
        "Treating your path as the path",
        "Philosophy that creates distance from the people who need you",
      ],
    },
    8: {
      do: [
        "Do the long, slow, important work — no shortcuts today",
        "Build something that requires patience to see its value",
        "Have the difficult ethical conversation that must happen",
        "Honor a commitment that is not easy to keep",
        "Do the methodical work that the long term requires",
        "Apply wisdom to the practical problem in front of you",
        "Teach through your behavior today, not your words",
        "Build the foundation even when the structure is not yet visible",
      ],
      avoid: [
        "Expanding before the foundation is ready",
        "Optimism that overrides what Saturn is trying to show you",
        "Quick fixes on problems that require real solutions",
        "Treating wisdom as a substitute for hard work",
        "Impatience with the pace of genuine growth",
        "Shortcuts that save time today and cost credibility later",
        "Using philosophy to rationalize avoiding the difficult task",
        "Wisdom that stays in the head and never reaches the hands",
      ],
    },
    9: {
      do: [
        "Start the principled project that requires both courage and ethics",
        "Take decisive action on something you believe in",
        "Lead from conviction — others will follow the energy",
        "Confront the injustice that needs confronting",
        "Make the bold ethical stand that has been needed",
        "Act with both speed and principle — do not sacrifice either",
        "Protect something or someone that cannot protect itself",
        "Use the fire in service of something that matters",
      ],
      avoid: [
        "Righteous anger without the wisdom to channel it",
        "Acting before the full picture is clear",
        "Aggression in defense of principle — the principle survives without it",
        "Moving faster than the situation requires",
        "Burning relationships in service of being right",
        "Courage without discernment is just impulsiveness",
        "Using principle as a weapon rather than a compass",
        "Starting what you cannot finish with the same conviction",
      ],
    },
  },

  // ══ BASIC 4 (Rahu) ═════════════════════════════════════════════════════════
  4: {
    1: {
      do: [
        "Ask one more clarifying question before deciding",
        "Verify claims independently before acting on them",
        "Take one step instead of the full leap today",
        "Get external perspective on a decision you are close to",
        "Read the fine print even when you trust the person",
        "Slow down the timeline — the urgency is manufactured",
        "Question the assumption that feels most obvious",
        "Separate what you know from what you have been told",
      ],
      avoid: [
        "Signing anything without reading every line",
        "Trusting authority figures without independent verification",
        "Ego moves that require you to look confident before you are",
        "Moving fast because others seem impatient",
        "Public commitments that have not been fully verified",
        "Decisions that depend on everything going right",
        "Assuming your read is accurate today",
        "Acting on the first impression in a high-stakes situation",
      ],
    },
    2: {
      do: [
        "Write what you are feeling before deciding based on it",
        "Postpone the emotional conversation until you are clearer",
        "Take 24 hours before responding to anything that upset you",
        "Seek grounding in routine rather than novelty today",
        "Reach out to someone who has your actual best interest in mind",
        "Identify what is real feeling versus Rahu-amplified anxiety",
        "Do something physical to discharge the restlessness",
        "Stay with what is proven rather than what is exciting",
      ],
      avoid: [
        "Major relationship decisions made while emotionally activated",
        "Trusting a new person too quickly — verify first",
        "Confusing intense feeling with accurate information",
        "Purchasing anything significant while emotionally unsettled",
        "Emotional revelations shared with the wrong person",
        "Romantic decisions made under the spell of the present moment",
        "Confusing drama with depth in a relationship",
        "Letting anxiety read as intuition",
      ],
    },
    3: {
      do: [
        "Consult someone with genuine experience before acting",
        "Question your optimistic assumptions with real data",
        "Learn from a mistake without dramatizing it",
        "Seek wisdom from someone who disagrees with you",
        "Look for the thing you have been overlooking in plain sight",
        "Trace the advice back to its original source",
        "Verify the teacher before trusting the teaching",
        "Study carefully — surface knowledge is dangerous today",
      ],
      avoid: [
        "Spiritual or philosophical shortcuts",
        "Guru-following without independent discernment",
        "Making large plans based on unverified beliefs",
        "Optimism without the numbers to back it",
        "Wisdom that conveniently confirms what you already wanted",
        "Learning that stays in theory and never becomes practice",
        "Overconfidence in new knowledge that has not been tested",
        "Treating enthusiasm for an idea as proof of its value",
      ],
    },
    4: {
      do: [
        "Sit with the uncertainty — clarity comes through patience here",
        "Use creative thinking to generate options, not decisions",
        "Research deeply before committing to anything",
        "Document your ideas without acting on them yet",
        "Create space between the impulse and the action",
        "Find the one thing that can be done without risk and do that",
        "Talk to someone who has navigated this exact situation before",
        "Acknowledge the confusion honestly instead of performing certainty",
      ],
      avoid: [
        "Any major financial or legal commitment today",
        "Impulsive changes to current stable situations",
        "Trusting the exciting new thing over the proven existing thing",
        "Decisions that cannot be undone — they can wait",
        "Commitments made under social or time pressure",
        "Acting on an insight before it has been tested",
        "Trusting anyone who says the opportunity expires today",
        "Double Rahu energy — do not make any permanent moves",
      ],
    },
    5: {
      do: [
        "Verify the financial information independently",
        "Research the opportunity thoroughly before committing",
        "Ask the financial expert the uncomfortable question",
        "Delay the commitment by one day if possible",
        "Run the numbers yourself instead of trusting someone else's",
        "Look for the hidden cost in the attractive deal",
        "Get the agreement in writing before acting on it",
        "Verify that what was promised is actually being delivered",
      ],
      avoid: [
        "Financial deals that require immediate decision",
        "Investments that promise unusually high returns",
        "Mixing money with relationships today",
        "Moving on a financial opportunity without a second opinion",
        "Contracts that cannot be reviewed before signing",
        "Treating financial excitement as financial judgment",
        "Lending or borrowing money under today's energy",
        "Letting FOMO drive a financial decision",
      ],
    },
    6: {
      do: [
        "Be honest about what you actually want in this relationship",
        "Invest in the relationship that has real substance, not just excitement",
        "Have the realistic conversation instead of the romantic one",
        "Do one grounding, ordinary thing together",
        "Verify the person's actions match their words over time",
        "Appreciate what is real rather than what is projected",
        "Create stability in a relationship rather than more intensity",
        "Choose depth over novelty in who you give time to today",
      ],
      avoid: [
        "Romantic commitments made under the current energy",
        "Financial decisions influenced by relationship pressure",
        "Confusing intensity with compatibility",
        "Telling yourself a story about someone their actions do not support",
        "Attractions that are exciting precisely because they feel unstable",
        "Giving more than you have verified is warranted",
        "Letting desire override the clear signal that something is off",
        "New romantic investments without due diligence",
      ],
    },
    7: {
      do: [
        "Trust the subtle warning signal — it is usually right in this period",
        "Ground yourself with physical routine before making any calls",
        "Sit in real silence and let answers form on their own",
        "Postpone the spiritually-inspired decision by one day",
        "Use Ketu's clarity to cut through Rahu's confusion",
        "Trust what has been consistent over time, not what is new and bright",
        "Do the spiritual practice that grounds rather than expands",
        "Let the insight settle for 24 hours before acting on it",
      ],
      avoid: [
        "Acting on spiritual insights without practical grounding",
        "Following a sudden revelation into irreversible action",
        "Psychic or intuitive claims made by strangers today",
        "Major decisions justified by signs or synchronicities",
        "Spiritual excitement as a substitute for discernment",
        "Treating the unusual as automatically meaningful",
        "Mystical thinking applied to practical decisions that need logic",
        "Sudden detachment from responsibilities that are still yours",
      ],
    },
    8: {
      do: [
        "Maintain what exists — do not build new, stabilize current",
        "Do the methodical work that does not require inspiration",
        "Pay off a debt or clear a backlog today",
        "Keep one commitment even when everything resists",
        "Protect what is already working before trying to grow it",
        "Do the maintenance that prevents bigger problems",
        "Hold the line on the boundary that has been tested",
        "Honor obligations even when the motivation is gone",
      ],
      avoid: [
        "New ventures, launches, or major changes today",
        "Forcing progress when resistance is complete",
        "Reacting to delays with anger — patience is the only path",
        "Adding new obligations to an already strained plate",
        "Decisions that require everything to cooperate simultaneously",
        "Using force where patience is the only thing that works",
        "Interpreting delay as failure",
        "Abandoning what is sound because it is slow",
      ],
    },
    9: {
      do: [
        "Move every physical action at half your normal speed",
        "Double-check before picking up, moving, or handling anything",
        "Drive slowly and leave earlier than needed",
        "Channel the energy into structured, controlled physical work",
        "Pause before every action today — this combination requires it",
        "Be especially careful with tools, vehicles, and sharp objects",
        "Do one thing at a time with full attention",
        "Check the path before stepping forward",
      ],
      avoid: [
        "Rushing in any physical context — this is the highest risk combination",
        "Impulsive physical actions without looking first",
        "Driving aggressively or handling tools carelessly",
        "Decisions made in anger — they backfire today",
        "Physical risk-taking of any kind",
        "Multitasking in situations that require singular focus",
        "Assuming the familiar route is still safe",
        "Emotional triggers that lead to physical reactivity",
      ],
    },
  },

  // ══ BASIC 5 (Mercury) ══════════════════════════════════════════════════════
  5: {
    1: {
      do: [
        "Close the business deal you have been building toward",
        "Make the negotiation call — your position is strong today",
        "Follow up on the money that should have arrived",
        "Send the pitch that needs to go",
        "Make the commercial decision with full confidence",
        "Put your commercial intelligence in a visible place",
        "Have the business conversation at the level it deserves",
        "Lock in the terms before the energy shifts",
      ],
      avoid: [
        "Arrogance in negotiation — confidence wins, arrogance loses",
        "Overextending the deal with unnecessary conditions",
        "Moving so fast you skip the detail that matters",
        "Letting the win become a lecture",
        "Confusing being smart with being right",
        "Pushing past a clear no when the deal is already done",
        "Using intelligence to dominate rather than to reach agreement",
        "Celebrating the deal before it is signed",
      ],
    },
    2: {
      do: [
        "Follow the intuitive commercial read — it is accurate",
        "Send the message you have been hesitating to send",
        "Have the honest conversation about money in a relationship",
        "Act on the financial gut feeling before it passes",
        "Trust the business insight that arrived without analysis",
        "Make the investment that feels both right and smart",
        "Follow the creative commercial instinct today",
        "Connect the emotional intelligence to the business decision",
      ],
      avoid: [
        "Emotional spending on things justified by mood",
        "Mixing personal feelings into financial decisions",
        "Waiting for perfect clarity before acting on a clear signal",
        "Overthinking after the instinct has already spoken",
        "Confusing what feels good with what is commercially sound",
        "Financial generosity that creates personal instability",
        "Letting emotional warmth override commercial discernment",
        "Making financial decisions from a place of fear or guilt",
      ],
    },
    3: {
      do: [
        "Invest in a course, book, or skill — it compounds",
        "Have the intelligent strategic conversation with someone wise",
        "Make the financial plan that requires long-term thinking",
        "Teach what you know — the act clarifies it further",
        "Apply wisdom to the financial decision in front of you",
        "Make the investment in capability over convenience",
        "Think about where this financial decision leads in five years",
        "Consult someone whose commercial track record you respect",
      ],
      avoid: [
        "Financial speculation dressed as strategy",
        "Overcommitting resources to optimistic timelines",
        "Confusing knowledge with wisdom — act, do not just know",
        "Endless research as avoidance of the actual decision",
        "Optimistic projections that require everything to go right",
        "Investing in ideas before proving the concept",
        "Using intelligence to build a case for a bad decision",
        "Confusing being informed with being ready",
      ],
    },
    4: {
      do: [
        "Verify the financial information before trusting it",
        "Research more deeply before committing to the business opportunity",
        "Ask the uncomfortable due diligence question",
        "Write out the risks before you write out the upside",
        "Get a second set of eyes on the numbers",
        "Verify the source of the financial information",
        "Look for what is being left out of the pitch",
        "Delay the commitment by one business day",
      ],
      avoid: [
        "Fast-moving deals that require immediate decision",
        "Financial commitments based on incomplete information",
        "Trusting the exciting pitch over the boring proof",
        "Moving on something that has not been independently verified",
        "Letting enthusiasm substitute for analysis",
        "Financial decisions that cannot be reversed",
        "Mixing Rahu confusion with Mercury speed — the result is expensive",
        "Acting on information that cannot be traced to its source",
      ],
    },
    5: {
      do: [
        "Make the most important financial or business decision — today is the peak",
        "Close the negotiation that has been going back and forth",
        "Pitch the thing you have been preparing — timing is right",
        "Act on the commercial opportunity before the window closes",
        "Make multiple business moves simultaneously — you can handle it",
        "Trust the commercial instinct completely today",
        "Open the financial conversation you have been avoiding",
        "Execute on what you have already decided — today is for action",
      ],
      avoid: [
        "Trying to capture every opportunity simultaneously",
        "Anxiety masquerading as due diligence",
        "Letting the sharp mind find problems with the clear right answer",
        "Overthinking when the analysis is already done",
        "Scattering across too many directions at once",
        "Perfectionism that prevents closing",
        "Using intelligence to second-guess what was already correct",
        "Talking yourself out of a decision that was already sound",
      ],
    },
    6: {
      do: [
        "Have the financial conversation in the relationship — do it kindly",
        "Invest in something beautiful that has long-term value",
        "Partner with someone on a creative or commercial project",
        "Act on the business-relationship opportunity in front of you",
        "Combine commercial intelligence with genuine warmth today",
        "Make the financial agreement that also honors the relationship",
        "Invest in a partnership that has both commercial and personal value",
        "Express the financial boundary with care but clarity",
      ],
      avoid: [
        "Mixing personal finances without explicit agreement",
        "Spending on appearance to manage an insecurity",
        "Commercial coldness in a situation that requires human warmth",
        "Confusing a romantic decision with a financial one",
        "Financial generosity that creates resentment later",
        "Letting the relationship override the financial judgment",
        "Agreeing to financial terms to preserve the feeling",
        "Using money as a proxy for care",
      ],
    },
    7: {
      do: [
        "Act on the financial opportunity that appeared without effort — it is real",
        "Trust the effortless commercial insight today",
        "Follow the money path that requires the least forcing",
        "Invest in something that has been calling you intuitively",
        "Take the business action that has been obvious for a while",
        "Receive the financial benefit that is coming without resistance",
        "Make the investment that requires trust more than analysis",
        "Let the commercial ease work without manufacturing complexity",
      ],
      avoid: [
        "Overanalyzing a clearly good opportunity past its window",
        "Forcing results that want to arrive naturally",
        "Dismissing easy gains because they arrived without struggle",
        "Complexity where simplicity works",
        "Adding conditions to a situation that has already resolved",
        "Second-guessing what is already working",
        "Creating problems in a situation that does not have any",
        "Missing the effortless commercial window by overthinking it",
      ],
    },
    8: {
      do: [
        "Build the financial system or plan that compounds over time",
        "Do the methodical analytical work — each step matters",
        "Review and optimize existing financial commitments",
        "Make the long-term investment decision with full information",
        "Do the financial planning that future you will thank you for",
        "Fix the recurring financial problem instead of working around it",
        "Build the commercial foundation before the visible structure",
        "Apply Mercury's precision to Saturn's long-term planning",
      ],
      avoid: [
        "Mercury speed versus Saturn timing — do not rush the deliberate decision",
        "Shortcuts in financial planning",
        "Expecting the systematic decision to produce quick results",
        "Abandoning a sound long-term plan for a faster short-term one",
        "Impatience with the pace of compound growth",
        "Confusing efficiency with shortcuts",
        "Treating the financial plan as done before it has been tested",
        "Moving to the next financial goal before the current one is stable",
      ],
    },
    9: {
      do: [
        "Make the bold competitive business move — timing is right",
        "Close the negotiation that requires nerve, not just intelligence",
        "Execute fast on the decision already made",
        "Take the commercial risk that others are hesitating on",
        "Move on the financial opportunity at full speed",
        "Make the aggressive commercial play that your preparation supports",
        "Act before the competitive window closes",
        "Put full Mercury precision behind full Mars energy today",
      ],
      avoid: [
        "Cutting verbal precision that damages relationships you need",
        "Competitive instinct overriding commercial judgment",
        "Reckless financial boldness justified as street smarts",
        "Burning bridges in a deal that requires future cooperation",
        "Speed that skips the verification step",
        "Aggression that turns a negotiation into a fight",
        "Overreaching in a position that is already strong",
        "Confusing boldness with recklessness in financial decisions",
      ],
    },
  },

  // ══ BASIC 6 (Venus) ════════════════════════════════════════════════════════
  6: {
    1: {
      do: [
        "Show up looking like the part — presentation matters today",
        "Lead a social or professional situation with warmth",
        "Put your name on something visible and beautiful",
        "Compliment the person who deserves to hear it",
        "Make the professional relationship warmer and more genuine",
        "Show grace in a situation that does not require it",
        "Invest in how you are perceived — it matters long-term",
        "Let charm and competence work together today",
      ],
      avoid: [
        "Vanity that reads as insecurity to others",
        "Using charm to avoid a real professional decision",
        "Spending on appearance to manage a confidence problem",
        "Letting social grace substitute for competent action",
        "Prioritizing how things look over how they actually are",
        "Performing warmth in a way that feels transactional",
        "Making professional decisions based on personal attraction",
        "Letting the desire to be liked override the need to be honest",
      ],
    },
    2: {
      do: [
        "Do something romantic or deeply affectionate today",
        "Create something together with someone you love",
        "Invest real time in the relationship — not quality time, real time",
        "Express what you actually feel — clearly",
        "Do the creative work that requires emotional vulnerability",
        "Give the relationship your undivided attention for a period",
        "Say the thing that would make the other person feel genuinely seen",
        "Make something beautiful together — the process matters as much as the result",
      ],
      avoid: [
        "Emotional decisions made in the flush of romantic feeling",
        "Using affection to avoid the difficult conversation",
        "Overspending on experiences to substitute for connection",
        "Confusing chemistry with compatibility",
        "Romantic expectations that are not being communicated",
        "Using beauty or comfort as a way to manage emotional distance",
        "Letting the aesthetic override the authentic",
        "Making relationship decisions based on how things feel right now",
      ],
    },
    3: {
      do: [
        "Give something genuinely and graciously — not for return",
        "Create something beautiful that expresses your values",
        "Invest in a cultural, artistic, or educational experience",
        "Nourish a relationship that deserves sustained care",
        "Do the generous thing that requires real thought and attention",
        "Share beauty in a way that includes rather than impresses",
        "Invest in wisdom that makes you more beautiful from the inside",
        "Combine generosity of spirit with generosity of presence",
      ],
      avoid: [
        "Overindulgence disguised as self-care",
        "Generosity that depletes you past your genuine capacity",
        "Aesthetic perfectionism that prevents finishing",
        "Spreading yourself across too many relationships",
        "Beauty without depth — surface refinement as identity",
        "Indulgence that borrows from tomorrow to pay for today",
        "Using generosity to manage guilt rather than express care",
        "Giving the beautiful thing when the honest thing is needed",
      ],
    },
    4: {
      do: [
        "Be honest about what you actually want in this connection",
        "Invest in the relationship with real substance, not just excitement",
        "Verify what is real before committing further",
        "Ask the question that will reveal whether this is what it appears",
        "Look at the pattern of behavior, not just the current feeling",
        "Slow the romantic momentum enough to see clearly",
        "Choose the relationship that is honest over the one that is beautiful",
        "Identify what you actually need versus what you are attracted to",
      ],
      avoid: [
        "Romantic or financial commitments made under Rahu influence",
        "Confusing attraction with trustworthiness",
        "Financial decisions influenced by wanting to impress",
        "Ignoring a clear warning sign in a relationship",
        "Letting beauty or charm override your better judgment",
        "New relationship investments without sufficient track record",
        "Confusing intensity with depth",
        "Making permanent romantic decisions on temporary feeling",
      ],
    },
    5: {
      do: [
        "Combine relationship warmth with a practical business conversation",
        "Partner with someone on something that serves both",
        "Make the financial decision that also honors the relationship",
        "Send the charming professional communication — it lands today",
        "Use Venus warmth to open a Mercury-driven conversation",
        "Make the partnership official with both commercial and personal terms",
        "Invest in a relationship that has both personal and professional value",
        "Have the financial conversation that the relationship needs",
      ],
      avoid: [
        "Mixing personal and financial without explicit clarity",
        "Using commercial coldness in a relational context",
        "Spending to manage relationship anxiety",
        "Agreeing to financial terms to preserve the feeling",
        "Letting personal warmth override commercial discernment",
        "Financial commitments to someone whose values you have not verified",
        "Using money to manage the emotional dynamic",
        "Treating the attractive option as the sound option",
      ],
    },
    6: {
      do: [
        "Do something genuinely restorative — not indulgent, actually nourishing",
        "Give yourself the thing you actually need today",
        "Create something beautiful with your full attention",
        "Invest in the relationship that feeds you",
        "Do the creative work for its own sake — not for recognition",
        "Spend time in an environment that genuinely restores you",
        "Appreciate beauty without needing to own it",
        "Give yourself permission to rest without guilt",
      ],
      avoid: [
        "Overconsumption justified by the good mood",
        "Substituting pleasure for genuine rest",
        "Relationships that take but do not give",
        "Indulgence that you will regret tomorrow",
        "Using beauty as an escape from a necessary truth",
        "Comfort as avoidance rather than restoration",
        "Double Venus — the pull toward excess is real today",
        "Confusing what is pleasant with what is good for you",
      ],
    },
    7: {
      do: [
        "Let the relationship or financial situation resolve naturally — it wants to",
        "Follow the aesthetic pull — your taste is excellent today",
        "Accept the easy gracious thing that is being offered",
        "Trust that things are moving without you needing to force them",
        "Receive what is coming with grace rather than suspicion",
        "Let ease be ease — do not manufacture complexity",
        "Do the creative work that flows rather than fighting for the difficult one",
        "Allow the beautiful thing to arrive in its own time",
      ],
      avoid: [
        "Forcing outcomes that are already coming",
        "Overthinking beauty into ugliness",
        "Rejecting easy gains because they arrived without effort",
        "Mistaking flow for complacency",
        "Adding resistance to a situation that is resolving on its own",
        "Discomfort with ease that makes you create problems",
        "Confusing surrender with defeat",
        "Letting perfectionism ruin what is already good",
      ],
    },
    8: {
      do: [
        "Commit fully to the relationship that deserves it — not casually",
        "Do the difficult relational work that must be done",
        "Invest in beauty that has lasting value",
        "Honor a commitment that is not easy to keep",
        "Do the sustained creative work — not just inspiration",
        "Build something beautiful that requires discipline to complete",
        "Make the long-term relationship investment with full awareness",
        "Choose depth over novelty in every relational decision today",
      ],
      avoid: [
        "Comfort-seeking as a substitute for the real conversation",
        "Spending on luxury to avoid a hard truth",
        "Confusing what is pleasant with what is right",
        "Relationships maintained by avoidance rather than choice",
        "Aesthetic indulgence as a distraction from what Saturn requires",
        "Venus comfort undermining Saturn discipline — they both matter",
        "Using beauty to avoid the harder inner work",
        "Relationships that feel good but are not growing",
      ],
    },
    9: {
      do: [
        "Channel the passionate energy into creative work that has fire",
        "Have the direct, honest conversation — warmth and clarity together",
        "Make the bold move in a relationship or creative project",
        "Create something that has real feeling behind it",
        "Use the intensity in service of something beautiful",
        "Pursue the creative project with total commitment",
        "Make the relationship move that requires both courage and care",
        "Turn passion into output rather than pressure",
      ],
      avoid: [
        "Romantic conflict — the intensity today leaves marks",
        "Passionate arguments that neither person will remember being worth it",
        "Aggression in creative or relational contexts",
        "Letting passion become pressure on another person",
        "Using intensity to force what should be invited",
        "Creative aggression that damages collaboration",
        "Emotional demands that come from the energy rather than the need",
        "Burning a relationship in a moment of passionate certainty",
      ],
    },
  },

  // ══ BASIC 7 (Ketu) ═════════════════════════════════════════════════════════
  7: {
    1: {
      do: [
        "Step into authority without waiting for permission",
        "Let the recognition arrive — stop chasing it",
        "Lead through quiet presence rather than loud announcement",
        "Act on the principled position — the support follows",
        "Do the thing that needs doing without requiring acknowledgment",
        "Let your track record speak before you do",
        "Be the authority through consistency, not assertion",
        "Hold the space without filling it with explanation",
      ],
      avoid: [
        "Recognition-seeking behavior that undermines what you are building",
        "Performing confidence instead of having it",
        "Forcing visibility when organic presence works better",
        "Authority that comes from ego rather than earned trust",
        "Talking about the work instead of doing it",
        "Needing the room to see what you are doing in order to do it",
        "Making your effort visible when the result should speak",
        "Announcements that precede the substance",
      ],
    },
    2: {
      do: [
        "Trust what your body is communicating today",
        "Follow the emotional signal that has no rational explanation",
        "Do the creative work that has been pulling you",
        "Connect with one person at real depth today",
        "Honor the sensitivity as information, not weakness",
        "Let the feeling complete itself without managing it",
        "Do the inner work that the emotional sensitivity is pointing to",
        "Trust the mood that does not make logical sense",
      ],
      avoid: [
        "Suppressing the subtle feeling because it is inconvenient",
        "Rationalizing what your intuition is already rejecting",
        "Isolation when the energy needs human contact",
        "Using sensitivity as a reason to avoid difficult truth",
        "Numbing the channel that is trying to give you information",
        "Treating emotional depth as a problem to be managed",
        "Letting the sharpness of feeling frighten you into avoidance",
        "Confusing emotional exhaustion with spiritual depth",
      ],
    },
    3: {
      do: [
        "Sit in real silence — even fifteen minutes changes the day",
        "Read something that challenges your current framework",
        "Seek wisdom from an unexpected source",
        "Reflect on the question that has no obvious answer",
        "Let the teaching come rather than seeking the teacher",
        "Practice what you already know before learning more",
        "Do the inner work that feels less dramatic than outer action",
        "Trust the wisdom that arrives through experience, not acquisition",
      ],
      avoid: [
        "Spiritual arrogance — you do not know as much as you think",
        "Using philosophy to avoid practical action",
        "Withdrawing from life in the name of spiritual work",
        "Certainty about things that require continued inquiry",
        "Teaching before you have done the work of learning",
        "Wisdom as performance rather than practice",
        "Treating detachment as wisdom when it is avoidance",
        "Spiritual bypassing of the practical responsibility in front of you",
      ],
    },
    4: {
      do: [
        "Trust the gut feeling that something is off — it is usually right",
        "Ground yourself physically before making any decisions",
        "Postpone the decision that does not feel ready",
        "Sit with the confusion until it resolves on its own",
        "Use Ketu clarity to cut through the Rahu confusion",
        "Trust the consistent thing over the exciting new thing",
        "Do the grounding practice that brings you back to yourself",
        "Let the instinct inform the decision before the analysis does",
      ],
      avoid: [
        "Acting on sudden spiritual insights without grounding them first",
        "Major decisions justified by signs, dreams, or gut alone",
        "Following someone's charismatic certainty without discernment",
        "Reacting to chaos with more chaos",
        "Ketu detachment meeting Rahu disruption — hold still",
        "Spiritual excitement that bypasses practical caution",
        "Letting the mystical override the material when both matter",
        "Major changes when the environment is already unstable",
      ],
    },
    5: {
      do: [
        "Act on the financial opportunity that appeared easily — it is real",
        "Trust the effortless commercial insight today",
        "Follow the money path that requires the least forcing",
        "Make the financial move that your instincts have been pointing to",
        "Receive the commercial benefit without manufacturing complexity",
        "Take the business action that has been obvious for a while",
        "Trust the financial ease as structurally real, not a trap",
        "Act before the window closes without analyzing it past its moment",
      ],
      avoid: [
        "Overanalyzing a good opportunity past its moment",
        "Forcing financial results that want to come naturally",
        "Dismissing easy gains because they feel too easy",
        "Complexity where clarity is already present",
        "Ketu detachment that becomes passivity in financial contexts",
        "Missing the effortless financial window by waiting for effort to validate it",
        "Spiritual non-attachment applied to financial opportunities that should be acted on",
        "Overthinking yourself out of an obvious good move",
      ],
    },
    6: {
      do: [
        "Let the relationship or situation resolve without pushing it",
        "Do the thing that brings you genuine peace — not entertainment",
        "Accept the grace being offered today",
        "Invest in relationships that nourish without effort",
        "Rest in the beauty that is already present",
        "Let affection flow naturally without managing it",
        "Create in the medium that feels effortless today",
        "Appreciate what is here without needing it to be different",
      ],
      avoid: [
        "Forcing outcomes that are already arriving",
        "Mistaking ease for complacency",
        "Rejecting what comes gracefully because it did not require struggle",
        "Holding onto what has naturally completed itself",
        "Manufacturing emotional intensity in a situation that has found peace",
        "Ketu detachment preventing you from fully receiving what Venus is offering",
        "Creating distance in a relationship that is asking for closeness",
        "Spiritual non-attachment that makes you unavailable to love",
      ],
    },
    7: {
      do: [
        "Do the inner work — meditate, reflect, sit in real stillness",
        "Follow the spiritual practice without needing results from it",
        "Ask the question that only silence can answer",
        "Trust the process even when no external progress is visible",
        "Honor the time that is meant for depth, not achievement",
        "Let go of the thing that is asking to be released",
        "Do the practice that strips away rather than adds",
        "Rest in the awareness that is always already present",
      ],
      avoid: [
        "Materialism on a day designed for depth",
        "Forcing spiritual experiences",
        "Comparing your path to others today",
        "Noise as a substitute for the stillness that actually nourishes you",
        "Double Ketu — the pull toward total withdrawal must be managed",
        "Detachment that becomes unavailability to the people who need you",
        "Using spirituality to avoid the practical reality in front of you",
        "Treating spiritual depth as an achievement to display",
      ],
    },
    8: {
      do: [
        "Do the consistent careful work — it is producing more than it appears",
        "Stay committed to what is right even when it is slow",
        "Build something that requires patience to appreciate",
        "Honor the process even when the outcome is invisible",
        "Trust that Ketu ease is working within Saturn's discipline",
        "Do the work without needing to see the full picture yet",
        "Keep the commitment even when the enthusiasm is gone",
        "Let the compound effect work without measuring it too early",
      ],
      avoid: [
        "Giving up on something closer to breakthrough than it looks",
        "Mistaking slow for stopped",
        "Forcing Saturn's pace to meet an arbitrary timeline",
        "Abandoning what is actually working because it feels invisible",
        "Ketu detachment undermining the Saturn consistency that is building something real",
        "Measuring progress too early in a long-term process",
        "Treating the absence of visible results as evidence of failure",
        "Restlessness that destroys what patience was building",
      ],
    },
    9: {
      do: [
        "Take the bold action that is backed by genuine conviction",
        "Move with courage on the thing you have been circling",
        "Lead through principled action — not loud assertion",
        "Put full energy behind the thing that matters most",
        "Act on what you know is right, not just what feels powerful",
        "Use the fire in service of the principle, not the ego",
        "Make the spiritually aligned bold move",
        "Combine Ketu insight with Mars execution today",
      ],
      avoid: [
        "Bold action without the conviction behind it",
        "Courage performed rather than felt",
        "Aggression toward what should be engaged with patiently",
        "Wasting the aligned energy on things that do not deserve it",
        "Ketu wisdom bypassed by Mars impulse",
        "Spiritual detachment that prevents necessary decisive action",
        "Moving with force where discernment is what is needed",
        "Using principle as a justification for aggression",
      ],
    },
  },

  // ══ BASIC 8 (Saturn) ═══════════════════════════════════════════════════════
  8: {
    1: {
      do: [
        "Do the hard visible work — let the output speak",
        "Make the long-game career decision others do not have patience for",
        "Follow through on a commitment that is inconvenient to keep",
        "Build the reputation through consistent action today",
        "Do the professional task that has real lasting consequences",
        "Show the kind of leadership that comes from earning it",
        "Make the decision that serves the long term even at short-term cost",
        "Be the person who is still there when the energy fades",
      ],
      avoid: [
        "Status moves that have not been backed by the work",
        "Expecting recognition today — it comes through accumulated effort",
        "Impatience with the timeline Saturn has set",
        "Announcing what you will do instead of doing it",
        "Leadership that serves the leader more than the mission",
        "Shortcuts on anything that carries your reputation",
        "Resenting the pace of genuine progress",
        "Confusing visibility with credibility",
      ],
    },
    2: {
      do: [
        "Keep the routine even when it feels pointless",
        "Reach out to one person — even briefly",
        "Do one emotionally difficult thing before anything else",
        "Be honest about how you actually feel to one safe person",
        "Maintain the structure that has been holding things together",
        "Connect briefly even if you do not have the energy for depth",
        "Do the small consistent action that prevents the larger collapse",
        "Trust that showing up in routine is enough today",
      ],
      avoid: [
        "Isolation — even five minutes of connection shifts the weight",
        "Self-criticism that adds to the already heavy load",
        "Numbing the feeling with screens or substances",
        "Canceling commitments that would require you to show up",
        "Letting the emotional heaviness make permanent decisions",
        "Treating the temporary weight as a permanent condition",
        "Withdrawing from everything rather than just what is truly optional",
        "Making decisions about long-term relationships from a Saturn-Moon low",
      ],
    },
    3: {
      do: [
        "Make the long-term investment that requires patience to see the value",
        "Have the ethical difficult conversation that must happen",
        "Build something meaningful even when the progress is invisible",
        "Commit to the right path even when the easy one is available",
        "Apply wisdom to the long-term problem in front of you",
        "Make the decision that will matter in five years, not five minutes",
        "Do the foundational work that makes everything else possible",
        "Honor the commitment that has integrity even when it costs something",
      ],
      avoid: [
        "Expanding before the foundation is genuinely ready",
        "Optimism that overrides what Saturn is trying to show you",
        "Quick fixes on problems that require real solutions",
        "Treating wisdom as a substitute for hard work",
        "Rushing the methodical process because you understand the theory",
        "Using knowledge to avoid the difficult practical task",
        "Building on an unstable foundation because the vision is clear",
        "Prioritizing growth over stability when stability is what is needed",
      ],
    },
    4: {
      do: [
        "Hold position — maintain what exists without adding to it today",
        "Do methodical work that does not require inspiration or momentum",
        "Clear a backlog, pay a debt, close an open loop",
        "Keep one commitment even when everything resists",
        "Protect what is working before trying to improve it",
        "Do the maintenance that prevents bigger problems",
        "Hold the boundary that has been tested",
        "Anchor to what is proven rather than what is possible",
      ],
      avoid: [
        "New ventures, launches, or expansions today",
        "Forcing progress when the resistance is complete",
        "Reacting to stagnation with impulsive action",
        "Adding new weight to what is already heavy",
        "Saturn delays meeting Rahu confusion — do not add a decision today",
        "Treating the block as a problem to overcome rather than information",
        "Expanding commitments when existing ones are already strained",
        "Making any permanent decision when nothing is moving",
      ],
    },
    5: {
      do: [
        "Do the detailed financial work — every number matters",
        "Make the long-term financial decision with full information",
        "Review and optimize existing financial systems",
        "Research before any financial commitment today",
        "Apply Saturn's discipline to Mercury's intelligence",
        "Build the financial system that will still be working in ten years",
        "Do the financial analysis that you have been postponing",
        "Make the methodical financial decision over the clever one",
      ],
      avoid: [
        "Mercury speed on a Saturn day — slow the process down",
        "Shortcuts in financial planning that create problems later",
        "Expecting immediate returns from deliberate long-term action",
        "Abandoning a sound plan because it is not exciting",
        "Financial cleverness that bypasses financial discipline",
        "Moving fast on a decision that Saturn requires to be slow",
        "Confusing efficiency with shortcuts",
        "Treating the long-term financial plan as done before it has been tested",
      ],
    },
    6: {
      do: [
        "Show up for the relationship that deserves full commitment",
        "Do the difficult relational work that genuine care requires",
        "Make the relationship decision based on real values, not convenience",
        "Honor a commitment that costs you something to keep",
        "Invest in the relationship that has proven itself over time",
        "Give the relationship the Saturn level of seriousness it deserves",
        "Do the long, consistent relational work that builds real trust",
        "Make the commitment with full awareness of what it requires",
      ],
      avoid: [
        "Comfort-seeking as a substitute for the real conversation",
        "Maintaining relationships through avoidance rather than genuine choice",
        "Spending on luxury to postpone an honest conversation",
        "Confusing Saturn discipline with emotional unavailability",
        "Using duty as a substitute for genuine care",
        "Relationships that persist through inertia rather than intention",
        "Confusing loyalty with love",
        "Venus comfort undermining the Saturn honesty the relationship needs",
      ],
    },
    7: {
      do: [
        "Do the sustained careful work — it is producing more than it appears",
        "Trust the slow process — it is moving toward something real",
        "Stay committed when results are invisible",
        "Do the one right thing even when nobody is watching",
        "Let Saturn's discipline serve Ketu's deeper purpose",
        "Trust that the invisible progress is still progress",
        "Hold to the practice even when the motivation is gone",
        "Do the work that compounds silently over time",
      ],
      avoid: [
        "Abandoning what is working because progress feels invisible",
        "Mistaking Ketu detachment for Saturn failure",
        "Giving up at the exact moment things are about to move",
        "Urgency that interrupts the deliberate process",
        "Ketu ease undermining the Saturn consistency that is required",
        "Measuring the long-term process with a short-term ruler",
        "Restlessness that breaks the compound effect",
        "Treating the absence of visible results as a reason to stop",
      ],
    },
    8: {
      do: [
        "Do the single most important difficult thing on your list",
        "Build what matters most — not what is easiest or fastest",
        "Complete what was started — follow-through today has compound value",
        "Repair something damaged — the repair holds permanently today",
        "Give everything to the one task that will actually matter",
        "Do the deep foundational work that cannot be delegated",
        "Show up with full effort and full attention simultaneously",
        "Honor the weight of this day by using it for what lasts",
      ],
      avoid: [
        "Every shortcut today — the return on them is the opposite of what you expect",
        "Emotional heaviness without the counterweight of genuine accomplishment",
        "Giving up at exactly the point the weight is teaching something",
        "Busyness that mimics productivity without producing it",
        "Double Saturn — the pull toward inaction must be resisted",
        "Letting the heaviness of the day justify doing less",
        "Spreading across many medium-effort things instead of one hard thing",
        "Treating difficulty as a sign to stop rather than a sign you are at the right place",
      ],
    },
    9: {
      do: [
        "Direct maximum effort toward the single most important task",
        "Do the physically and professionally demanding work — full capacity today",
        "Build relentlessly toward the thing that matters most",
        "Sustained high-output work today converts into permanent results",
        "Use Mars energy to break through the Saturn resistance",
        "Give the most difficult task the most energy",
        "Work at the level that Saturn will reward over time",
        "Let Mars urgency serve Saturn's long-term purpose",
      ],
      avoid: [
        "Spreading Saturn-Mars energy across too many directions",
        "Mars aggression bypassing Saturn wisdom — anger decisions today are permanent",
        "Ignoring physical and emotional signals — the body needs attention today",
        "Intensity without direction — pick the one target",
        "Using the high-energy day for low-leverage tasks",
        "Letting urgency bypass the discernment that Saturn requires",
        "Physical overexertion that costs more tomorrow than it produces today",
        "Anger at the pace of progress when the pace is appropriate",
      ],
    },
  },

  // ══ BASIC 9 (Mars) ═════════════════════════════════════════════════════════
  9: {
    1: {
      do: [
        "Make the bold leadership move — full authority and energy available",
        "Confront the thing that needs confronting — do it now",
        "Take the competitive professional action you have been hesitating on",
        "Lead decisively — others will follow the energy today",
        "Make the move that requires both courage and authority",
        "Claim the position that your track record has earned",
        "Act first in the situation that rewards decisiveness",
        "Use the full-power window for the most important leadership action",
      ],
      avoid: [
        "Unnecessary battles — the power today is real and so is the cost of misusing it",
        "Anger bypassing the authority you actually have",
        "Recklessness that wastes the full-power window",
        "Ego driving decisions that clear-headed authority would make better",
        "Making the leadership move to prove a point rather than produce a result",
        "Burning the goodwill that the authority requires to function",
        "Treating boldness as a substitute for wisdom",
        "Starting conflicts that distract from the real leadership task",
      ],
    },
    2: {
      do: [
        "Channel the emotional intensity into physical movement",
        "Write or create to process what you are feeling",
        "Have the direct honest emotional conversation — not the explosive one",
        "Connect physically — the body absorbs the intensity productively",
        "Use the fire to complete the creative work, not to start a conflict",
        "Express the feeling clearly before it becomes reactive",
        "Do the physical work that uses the intensity well",
        "Channel Mars energy through the Moon's creative depth",
      ],
      avoid: [
        "Arguments at home — emotional heat today leaves lasting marks",
        "Reactive messages or calls when emotionally activated",
        "Letting passion become aggression in close relationships",
        "Suppressing until the pressure forces an explosion",
        "Making permanent relationship decisions in the intensity of the moment",
        "Words in anger that undo months of trust",
        "Using the emotional intensity to force a resolution before its time",
        "Physical reactivity that comes from emotional pressure",
      ],
    },
    3: {
      do: [
        "Start the principled project that requires both courage and conviction",
        "Take decisive action on something you genuinely believe in",
        "Lead with both strength and ethics — the combination is rare and powerful",
        "Confront the injustice that needs confronting, wisely",
        "Make the bold ethical stand that has been needed",
        "Act on the principle with full Mars commitment",
        "Use the fire in service of something worth burning for",
        "Combine Jupiter wisdom with Mars execution today",
      ],
      avoid: [
        "Righteous aggression that undermines the principle you are defending",
        "Acting before you have the full picture",
        "Moralizing through force rather than example",
        "Burning a bridge you will need to cross again",
        "Conviction without discernment is just stubbornness",
        "Using principle as a weapon rather than a compass",
        "Aggression disguised as righteousness",
        "Moving so fast the wisdom cannot keep up with the action",
      ],
    },
    4: {
      do: [
        "Move every physical action at half speed today",
        "Drive slowly, handle tools carefully, double-check before acting",
        "Channel the Mars energy into structured, controlled work",
        "Leave earlier, take fewer risks, be more deliberate than usual",
        "Pause before every physical action — this combination requires it",
        "Do one thing at a time with complete attention",
        "Be especially careful with vehicles, tools, and sharp objects",
        "Treat the familiar route as if it requires fresh attention",
      ],
      avoid: [
        "Rushing in any form — this is the highest physical risk combination",
        "Impulsive physical actions without looking first",
        "Decisions made in anger — they backfire with unusual severity today",
        "Speed as a substitute for attention",
        "Physical risk-taking of any kind",
        "Emotional triggers that lead to physical reactivity",
        "Multitasking in situations that require singular attention",
        "Assuming the familiar is safe without checking",
      ],
    },
    5: {
      do: [
        "Execute on the decision already made — speed and accuracy both available",
        "Close the competitive negotiation or business deal today",
        "Make the bold commercial move others are hesitating on",
        "Follow through on the financial commitment at full speed",
        "Use Mars urgency and Mercury precision simultaneously",
        "Act on the commercial opportunity before the window closes",
        "Close multiple things in quick succession — you can do it today",
        "Move with the confidence that preparation earns",
      ],
      avoid: [
        "Verbal sharpness that damages relationships you will need later",
        "Competitive instinct overriding commercial judgment",
        "Reckless boldness justified as street smarts",
        "Finishing one thing before starting the next — do not scatter",
        "Speed that bypasses the verification step",
        "Aggression that turns a negotiation into a fight",
        "Using the commercial energy to prove dominance rather than close the deal",
        "Moving so fast you miss the signal that something is wrong",
      ],
    },
    6: {
      do: [
        "Channel the passionate energy into creative work with real fire behind it",
        "Make the bold move in a relationship or creative project",
        "Express what you feel directly — warmth and clarity together",
        "Create something that has genuine passion in every part of it",
        "Use the intensity to complete the creative work that has been stalling",
        "Make the relationship move that requires both courage and care",
        "Turn Venus warmth and Mars fire into something beautiful and lasting",
        "Give the creative project the full Mars commitment today",
      ],
      avoid: [
        "Romantic conflict — the intensity today leaves marks that outlast the reason",
        "Passion that becomes pressure on another person",
        "Aggression in creative contexts that should have warmth",
        "Burning bridges in a relationship that deserves better",
        "Using the passionate energy to demand rather than invite",
        "Intensity that overwhelms instead of connecting",
        "Creative aggression that damages the collaboration",
        "Letting Mars impatience ruin what Venus was building",
      ],
    },
    7: {
      do: [
        "Take the bold action that is backed by real conviction — not just energy",
        "Move on the thing you have been building toward — timing is right",
        "Combine courage with trust — act and let the outcome arrive",
        "Give full effort to the one thing that deserves it most today",
        "Let Ketu's alignment guide Mars's energy precisely",
        "Act from the place of knowing, not the place of wanting",
        "Use the aligned energy for the action that has been waiting",
        "Trust that the right action and the powerful action are the same today",
      ],
      avoid: [
        "Bold action without genuine conviction behind it",
        "Courage as performance rather than felt truth",
        "Forcing the outcome that wants to arrive naturally with a little push",
        "Wasting the high-alignment energy on unworthy targets",
        "Mars urgency overriding Ketu's clear directional signal",
        "Action for action's sake when discernment is what is needed",
        "Spending the aligned window on what is loud instead of what matters",
        "Courage directed at the wrong target",
      ],
    },
    8: {
      do: [
        "Do the most demanding work available — physical and professional capacity is at peak",
        "Sustained high output today converts into permanent results",
        "Give everything to the most important single thing on your list",
        "Build relentlessly toward the thing that matters most today",
        "Use Mars intensity to break through what Saturn has been slowly building toward",
        "Do the hard physical and mental work simultaneously — you can hold both today",
        "Complete the thing that has been demanding full effort",
        "Let the intensity of this day make a permanent mark on what you are building",
      ],
      avoid: [
        "Spreading the energy across too many directions — pick one target",
        "Mars impatience meeting Saturn blocking — the block is the teacher today",
        "Anger when the path resists — patience is the only thing that moves it",
        "High intensity without direction",
        "Overexertion that costs more tomorrow than it produces today",
        "Using the physical energy to avoid the mental work that Saturn requires",
        "Letting Mars urgency bypass the Saturn discipline that makes the effort compound",
        "Full effort in the wrong direction",
      ],
    },
    9: {
      do: [
        "Aim everything at one external challenge that deserves the full force",
        "Do the most physically and professionally demanding thing available",
        "Compete at full capacity — the energy is real and the window is today",
        "Give maximum to the one thing most worth giving it to",
        "Use double Mars to complete what single Mars would leave unfinished",
        "Make the competitive move that requires more energy than most people have",
        "Channel every bit of the intensity into the single most important output",
        "Do the thing that would have been impossible on a lesser day",
      ],
      avoid: [
        "Turning the energy inward — self-attack or rumination today is costly",
        "Legal and physical risks are genuinely elevated today — pause before aggression",
        "Arguments that exist for the sake of the energy needing an outlet",
        "Double Mars finding conflict where none was necessary",
        "Physical recklessness that wastes the capacity on something irreversible",
        "Letting the aggression choose the target instead of choosing it yourself",
        "Intensity that burns relationships you will need after the energy fades",
        "Confusing the power of the day with permission to be destructive",
      ],
    },
  },
};
