// ═══════════════════════════════════════════════════════════════════════════════
// AASTROSPHERE — BREAKDOWN LIBRARY
// Per-day (weekly), per-week (monthly), per-month (yearly) detail predictions
// Completely new content — not from existing prediction library
// ═══════════════════════════════════════════════════════════════════════════════

// ─── Daily character by number ────────────────────────────────────────────────
// What each daily number MEANS for that specific day — fresh, specific content
export const DAY_CHARACTER = {
  1: {
    label: 'Authority Day',
    headline: 'Lead, initiate, be visible.',
    character: 'This is a forward-moving day. Decisions made with confidence tend to stick. The natural energy pushes toward beginnings — starting conversations, taking positions, making asks.',
    good_for: [
      'Making the ask you have been postponing',
      'Career-related decisions and conversations',
      'Starting something new — a project, a routine, a conversation',
      'Anything that requires confidence and directness',
      'Negotiations where you need to hold your ground',
    ],
    watch_out: [
      'Ego driving decisions that wisdom should be making',
      'Coming across as aggressive when directness was the intent',
      'Starting fights to prove a point that could have been ignored',
    ],
    money: 'Income decisions made today tend to hold. Bold financial moves are backed by the day.',
    relationships: 'Good day to express what you want clearly. Not the day for subtle hints.',
    energy: 'High. Mental clarity is sharp. Physical energy is available.',
  },
  2: {
    label: 'Connection Day',
    headline: 'Connect, feel, create.',
    character: 'A day for depth over speed. Emotional intelligence is running high — you read people accurately. Creative work flows. Conversations go deeper than usual when you let them.',
    good_for: [
      'Meaningful conversations with people who matter',
      'Creative and artistic work',
      'Expressing something you have been holding back',
      'Reaching out to someone you have been meaning to contact',
      'Work that requires reading people and situations',
    ],
    watch_out: [
      'Making financial decisions from emotional reasoning',
      'Taking criticism more personally than it was meant',
      'The mood swings that come with elevated sensitivity',
    ],
    money: 'Not the strongest financial day. Avoid major money decisions. Income through people and creative work is favored.',
    relationships: 'The best day of the week for relationship investment. What is said today lands deeper.',
    energy: 'Moderate. Emotional energy is high. Physical energy is secondary today.',
  },
  3: {
    label: 'Clarity Day',
    headline: 'Think clearly, advise well, plan.',
    character: 'The sharpest thinking day. Analysis, planning, and advice all operate at a higher level. Good decisions made today tend to be genuinely good — the clarity is real, not overconfidence.',
    good_for: [
      'Planning and strategic thinking',
      'Important writing — emails, proposals, documents',
      'Giving or seeking advice on something that matters',
      'Learning something new or researching deeply',
      'Conversations requiring nuance and good judgment',
    ],
    watch_out: [
      'Ethical shortcuts — this day amplifies the consequences',
      'Over-explaining or lecturing when a conversation was all that was needed',
      'Holding others to the same standard you hold yourself',
    ],
    money: 'Good day for financial planning and strategy. Not impulsive — methodical.',
    relationships: 'Wisdom is available for relationship conversations. A good day to address something that needs addressing.',
    energy: 'Clear and steady. Not high energy — focused energy.',
  },
  4: {
    label: 'Research Day',
    headline: 'Research, analyze, do not commit.',
    character: 'The ground is less stable today. Plans that seemed solid need checking. The research ability is genuinely sharp — this is a good day to investigate, not to execute. What you discover today matters.',
    good_for: [
      'Research and investigation',
      'Understanding something complex before acting on it',
      'Background checking and fact verification',
      'Technology and analytical work',
      'Discovering what you did not know you needed to know',
    ],
    watch_out: [
      'Impulsive purchases — the spending impulse is strongest on this day',
      'Committing to plans that have not been independently verified',
      'Trusting attractive opportunities without checking them',
      'Financial decisions based on projection rather than confirmed data',
    ],
    money: 'Caution day for finances. Best use: analyze and plan. Worst use: spend or commit.',
    relationships: 'Unexpected developments in relationships are possible. Navigate carefully.',
    energy: 'Scattered but bright. The mind runs fast. Ground it in research rather than action.',
  },
  5: {
    label: 'Business Day',
    headline: 'Negotiate, earn, communicate.',
    character: 'The sharpest business day of the week. Financial intelligence is at its most accurate. Communication is persuasive. Deals made today tend to hold. The calculator is running well.',
    good_for: [
      'Negotiations and deal-making',
      'Financial decisions of any size',
      'Business conversations and pitches',
      'Communication that needs to be convincing',
      'Closing what has been in progress',
    ],
    watch_out: [
      'Overthinking that converts good decisions into anxiety',
      'Letting the sharp mind run past midnight — sleep is the cost',
      'Cold efficiency that alienates people who could be allies',
    ],
    money: 'Best financial day of the cycle. The instinct is accurate. Act on it.',
    relationships: 'Secondary priority today — and that is fine. One meaningful check-in keeps the balance.',
    energy: 'High and slightly anxious. Mental energy is extraordinary. Physical follows.',
  },
  6: {
    label: 'Harmony Day',
    headline: 'Create, connect, express.',
    character: 'Beauty and connection are the day\'s themes. Creative work flows. Social interactions are warmer than usual. The desire for aesthetic and relational richness is strong — and the day supports it.',
    good_for: [
      'Creative work of any kind',
      'Social events and important social interactions',
      'Expressing appreciation to someone who deserves it',
      'Romantic investment',
      'Anything requiring presentation and charm',
    ],
    watch_out: [
      'Harsh words when frustrated — the tongue is sharper than usual today',
      'Overspending on beauty and experience',
      'Confusing attraction for compatibility in new connections',
    ],
    money: 'Spending day more than earning day. Income through creative work is favored.',
    relationships: 'Best day for romantic and social investment. What is expressed today lands unusually well.',
    energy: 'Warm and social. Creative energy is high.',
  },
  7: {
    label: 'Fortune Day',
    headline: 'Trust instinct, take the chance.',
    character: 'Luck is structurally present today. Things have a way of working out when you show up for them. The intuition is more accurate than usual. Decisions made from genuine instinct — not analysis — tend to be right.',
    good_for: [
      'The ask or decision you have been overthinking',
      'Important meetings and key conversations',
      'Travel and change of environment',
      'Following a hunch that logic has been overriding',
      'Spiritual and reflective work',
    ],
    watch_out: [
      'Overthinking instead of acting — analysis is less reliable than instinct today',
      'Forcing outcomes instead of allowing what wants to arrive',
      'Anxiety disguising itself as intuition',
    ],
    money: 'Lucky financial day. Unexpected income possible. The right opportunity should be acted on.',
    relationships: 'Deep intuitive connection available. The conversation that needed to happen, happens.',
    energy: 'Calm and fortunate. Less driven by effort, more by alignment.',
  },
  8: {
    label: 'Work Day',
    headline: 'Effort, discipline, compound.',
    character: 'A day for sustained effort. Not the flashiest day — the most durable one. What is built today through genuine discipline holds. The karmic quality of this day means shortcuts cost more than they save.',
    good_for: [
      'The hard work that has been avoided',
      'Completing something that was started',
      'Physical work and exercise',
      'Building systems and routines',
      'Anything that requires patience and persistence',
    ],
    watch_out: [
      'Shortcuts — the consequences multiply on this day',
      'Expecting immediate feedback from today\'s effort',
      'The emotional heaviness that can accompany this energy',
    ],
    money: 'Earned income day. Slow but genuine. Not the day for quick financial moves.',
    relationships: 'The relationship benefits from sustained effort today, not grand gestures.',
    energy: 'Steady and deep. Not high — durable.',
  },
  9: {
    label: 'Energy Day',
    headline: 'Move, compete, act boldly.',
    character: 'Maximum energy day. Physical capacity is high. Competitive instinct is sharp. Bold moves tend to land. The catch is that the aggression is also at its most available — directed well, it builds things; undirected, it creates conflict.',
    good_for: [
      'Physical activity and sport',
      'Competitive situations of any kind',
      'Bold decisions that require courage',
      'High-output work sessions',
      'Confronting something that has been avoided',
    ],
    watch_out: [
      'Starting conflicts that drain energy needed elsewhere',
      'Recklessness disguised as boldness',
      'The frustration spike when blocked — pause before responding',
    ],
    money: 'Bold income day. Action converts to income. Risk is warranted, recklessness is not.',
    relationships: 'Passionate and intense. Love and conflict run at the same frequency today.',
    energy: 'Maximum. The body and mind are both running hot.',
  },
};

// ─── Week character by dominant number ────────────────────────────────────────
export const WEEK_CHARACTER = {
  1: {
    label: 'Authority Week',
    character: 'A week where initiatives, bold moves, and career decisions have their strongest backing. Leadership energy runs throughout.',
    good_for: ['Career moves and negotiations', 'Starting important projects', 'Public-facing work', 'Making asks'],
    watch_out: ['Ego-driven conflicts', 'Overextending authority'],
    finance: 'Strong income week. Bold moves earn.',
    relationships: 'Lead with confidence. Direct communication works.',
  },
  2: {
    label: 'Connection Week',
    character: 'A week for depth in relationships and creative work. Emotional intelligence peaks. Important conversations go deeper than usual.',
    good_for: ['Relationship investment', 'Creative work', 'Meaningful conversations', 'Collaboration'],
    watch_out: ['Financial decisions from emotional reasoning', 'Taking things too personally'],
    finance: 'Income through relationships and creative work.',
    relationships: 'The most relationship-rich week of the period.',
  },
  3: {
    label: 'Clarity Week',
    character: 'A week for thinking clearly, advising well, and making plans that will hold. Wisdom is accessible and applicable.',
    good_for: ['Strategic planning', 'Important writing and communication', 'Advisory work', 'Learning'],
    watch_out: ['Ethical shortcuts amplified this week', 'Over-explaining'],
    finance: 'Financial planning week. Strategy over impulse.',
    relationships: 'Good week for addressing what needs addressing calmly.',
  },
  4: {
    label: 'Research Week',
    character: 'A week for investigation and analysis, not for committing. The discoveries made this week prepare the ground for next week\'s action.',
    good_for: ['Research and investigation', 'Technology work', 'Understanding before acting'],
    watch_out: ['Impulsive financial decisions', 'Committing to unverified plans'],
    finance: 'Caution week for finances. Research, do not commit.',
    relationships: 'Unexpected developments. Navigate with patience.',
  },
  5: {
    label: 'Business Week',
    character: 'The sharpest business week. Financial decisions and negotiations have maximum backing. Communication is persuasive.',
    good_for: ['Deals and negotiations', 'Financial decisions', 'Business conversations', 'Closing'],
    watch_out: ['Overthinking good opportunities', 'Anxiety from the mental pace'],
    finance: 'Best financial week of the cycle.',
    relationships: 'Business over personal this week.',
  },
  6: {
    label: 'Harmony Week',
    character: 'A week where creative work, social connection, and aesthetic investment all flow. Beauty and warmth are available.',
    good_for: ['Creative work', 'Social events', 'Romantic investment', 'Presentation'],
    watch_out: ['Overspending on aesthetics', 'Harsh speech when frustrated'],
    finance: 'Income through creative work. Spending impulse is elevated.',
    relationships: 'Most socially active week.',
  },
  7: {
    label: 'Fortune Week',
    character: 'A week where things have an unusual tendency to work out. Luck is present. Instinct outperforms analysis.',
    good_for: ['Important asks and decisions', 'Travel', 'Following hunches', 'Key meetings'],
    watch_out: ['Overthinking instead of acting', 'Forcing outcomes'],
    finance: 'Lucky financial week. Act on what presents itself.',
    relationships: 'Intuitive connection available.',
  },
  8: {
    label: 'Work Week',
    character: 'A week for sustained effort that compounds. Not glamorous — durable. What is built this week holds.',
    good_for: ['Hard focused work', 'Completing what was started', 'Physical work', 'Building systems'],
    watch_out: ['Shortcuts that cost more this week', 'Emotional heaviness'],
    finance: 'Earned income week. Slow but genuine.',
    relationships: 'Effort over grand gestures.',
  },
  9: {
    label: 'Energy Week',
    character: 'Maximum energy week. Physical capacity, competitive instinct, and bold action are all available. The aggression needs direction.',
    good_for: ['Physical activity', 'Competition', 'Bold career moves', 'High-output work'],
    watch_out: ['Unnecessary conflicts', 'Recklessness', 'Frustration spikes'],
    finance: 'Bold income week. Action converts.',
    relationships: 'Passionate and potentially volatile.',
  },
};

// ─── Month character by number ────────────────────────────────────────────────
export const MONTH_CHARACTER = {
  1: {
    label: 'Authority Month',
    character: 'A month driven by ambition, recognition, and leadership. Career moves made this month carry weight. The natural energy supports bold action and visibility.',
    best_for: ['Career advancement', 'Starting important projects', 'Leadership decisions', 'Public recognition'],
    caution: ['Ego-driven conflicts cost more this month', 'Overextension of authority'],
    finance: 'Strong income month. Bold financial moves are backed.',
    relationships: 'Direct communication works. Lead with clarity.',
    health: 'Head and heart carry the month\'s tension — manage both.',
  },
  2: {
    label: 'Connection Month',
    character: 'A month for depth — in relationships, creative work, and emotional intelligence. What is felt this month runs deeper than usual.',
    best_for: ['Relationship investment', 'Creative projects', 'Emotional honesty', 'Collaboration'],
    caution: ['Financial decisions made from emotional reasoning', 'Sensitivity running high'],
    finance: 'Income through relationships and creative work.',
    relationships: 'Most relationship-rich month of the cycle.',
    health: 'Sleep and emotional regulation are the priorities.',
  },
  3: {
    label: 'Wisdom Month',
    character: 'A month where clarity, good judgment, and wisdom are accessible. Decisions made this month tend to be genuinely good ones.',
    best_for: ['Strategic planning', 'Learning and studying', 'Advisory work', 'Important writing'],
    caution: ['Ethical shortcuts amplify this month', 'Lecturing instead of listening'],
    finance: 'Financial planning and expertise-based income.',
    relationships: 'Good month to address what has been avoided.',
    health: 'Liver and ethical stress — watch what you consume.',
  },
  4: {
    label: 'Research Month',
    character: 'A month for investigation and understanding, not for committing. Financial caution is essential. The discoveries made this month set up future action.',
    best_for: ['Research and investigation', 'Technology work', 'Understanding complex situations'],
    caution: ['All major financial commitments', 'Unverified plans', 'Attractive opportunities without checking'],
    finance: 'Hold major financial decisions. Research mode.',
    relationships: 'Unexpected developments — navigate with patience.',
    health: 'Blood pressure and recklessness risk elevated.',
  },
  5: {
    label: 'Business Month',
    character: 'The sharpest business month. Financial intelligence is at peak. Deals made this month hold. Communication is most persuasive.',
    best_for: ['Major financial decisions', 'Deals and negotiations', 'Business launches', 'Income generation'],
    caution: ['Anxiety from the mental pace', 'Overthinking past the opportunity'],
    finance: 'Best financial month of the cycle.',
    relationships: 'Professional over personal — make the explicit investment.',
    health: 'Sleep is the non-negotiable. Anxiety management is essential.',
  },
  6: {
    label: 'Harmony Month',
    character: 'A month for creative and romantic investment. Beauty, connection, and aesthetic richness are available. Spending matches the income.',
    best_for: ['Creative work', 'Romantic investment', 'Social events', 'Aesthetic projects'],
    caution: ['Overspending on beauty and experience', 'Harsh speech when frustrated'],
    finance: 'Income through creative work. Spending impulse is elevated.',
    relationships: 'Most romantically and socially active month.',
    health: 'Hormonal balance and hydration need attention.',
  },
  7: {
    label: 'Fortune Month',
    character: 'Lucky month. Things have an unusual tendency to work out. Instinct is more reliable than analysis. Unexpected income possible.',
    best_for: ['Important asks and decisions', 'Travel', 'Following intuition', 'Key meetings'],
    caution: ['Overthinking instead of acting', 'Instability if multiple 7s are present'],
    finance: 'Lucky financial month. Unexpected income possible.',
    relationships: 'Deep intuitive connections available.',
    health: 'Sleep and nervous system — the intuition requires rest.',
  },
  8: {
    label: 'Karma Month',
    character: 'A month for sustained effort that compounds. Shortcuts cost more. What is built with discipline and integrity holds.',
    best_for: ['Hard sustained work', 'Long-term projects', 'Physical work', 'Ethical decisions'],
    caution: ['Shortcuts and compromises cost triple', 'Emotional heaviness'],
    finance: 'Earned income. Slow but genuine accumulation.',
    relationships: 'Sustained effort over grand gestures.',
    health: 'Dental, gut, and joints carry the month\'s pressure.',
  },
  9: {
    label: 'Energy Month',
    character: 'Maximum energy month. Physical capacity, competitive instinct, and bold action are available. The aggression needs a directed channel.',
    best_for: ['Physical activity', 'Competitive situations', 'Bold career moves', 'High output work'],
    caution: ['Unnecessary conflicts drain the month', 'Recklessness', 'Legal risks from anger'],
    finance: 'Bold income month. Action converts.',
    relationships: 'Passionate and potentially volatile.',
    health: 'Physical outlet is mandatory — daily.',
  },
};

