// ═══════════════════════════════════════════════════════════════════════════════
// AASTROSPHERE — DAILY QUOTES LIBRARY
// 100 quotes per daily number = 900 total
// Selected by: (basic + destiny + maha + antar + monthly + daily) % 100
// Each quote relevant to that day's energy
// ═══════════════════════════════════════════════════════════════════════════════

export const DAILY_QUOTES = {

  // ── Daily 1 — Sun day ─────────────────────────────────────────────────────
  // Authority, initiative, boldness, visibility, leadership
  1: [
    "Today you lead. Stop waiting for permission.",
    "The move you keep postponing — today is the right time.",
    "Your instinct today is sharper than most people's analysis.",
    "Confidence isn't arrogance when it's backed by preparation.",
    "The window is open. Walk through it.",
    "Today asks for boldness, not perfection.",
    "You already know what to do. Do it.",
    "Leadership isn't a title. Today it's a choice.",
    "The bold ask gets the bold answer.",
    "Don't shrink today. This energy doesn't repeat for a while.",
    "Authority without ego — that's what today rewards.",
    "The person waiting for a sign — this is it.",
    "Initiate. Don't react. Today the first mover wins.",
    "What you start today carries unusual momentum.",
    "Your presence alone changes the room today.",
    "The hesitation you feel is habit, not wisdom.",
    "Today rewards action. Analysis can wait one day.",
    "Speak first. The room is ready to follow.",
    "The opportunity that looks too big — it isn't.",
    "Be visible today. You're exactly where you're supposed to be.",
    "Decisiveness is a skill. Today you have it in full.",
    "The energy today is behind you, not in front of you.",
    "Don't give someone else credit for a move you should be making.",
    "Today's confidence is earned, not assumed.",
    "Make the call. Send the message. Take the meeting.",
    "The idea that won't leave you alone — act on it today.",
    "Your opinion matters today. Share it.",
    "Today is not for waiting. It's for starting.",
    "The person in the room with the most clarity today is you.",
    "Back yourself. The chart is backing you.",
    "What you do today will be visible for longer than you expect.",
    "The momentum begins when you decide it does.",
    "Don't negotiate with the fear. Just move.",
    "Every bold thing started on a day exactly like today.",
    "You weren't built to stand in the back of the room.",
    "The answer to your biggest question right now is yes.",
    "Do the thing that requires courage first.",
    "Today your word carries weight. Use it carefully and fully.",
    "The version of you that hesitates — not today.",
    "Stop convincing yourself. Start executing.",
    "The right time is rarely perfect. Today is close enough.",
    "What you pursue today, you catch.",
    "Initiative is today's currency. Spend it.",
    "Your energy today is a resource. Don't waste it on small things.",
    "The vision is clear. The path is open. Move.",
    "Others will follow today if you go first.",
    "Don't confuse careful with scared.",
    "The risk you're considering — it's smaller than it looks.",
    "Today you have permission to want what you want.",
    "The fire in you today — use it before it cools.",
    "Your instincts have been right before. Trust them again.",
    "Today is a day to be remembered for something.",
    "The bolder the move, the cleaner the outcome today.",
    "Doubt is a visitor. Action is the resident.",
    "The version of this story where you win — it starts today.",
    "Your clarity today is a gift. Act on it.",
    "The one who waits for perfect conditions waits forever.",
    "Today your energy walks into the room before you do.",
    "What you claim today, you keep.",
    "The door is open. You just have to notice it.",
    "Today is not the day to play small.",
    "Your confidence is not arrogance — it's earned.",
    "The thing holding you back today is a story, not a fact.",
    "Go first. Others will catch up.",
    "Today the universe is behind the bold decision.",
    "Start before you're ready. That's what today is for.",
    "The version of you that acts — that's today's version.",
    "What you ask for today, you have a real chance of receiving.",
    "Today your presence is the strategy.",
    "Don't explain. Just execute.",
    "The path is open. The timing is right. Move.",
    "Your gut today is running at full accuracy.",
    "Today is a day of beginnings. Begin something.",
    "The fear is smaller than the opportunity.",
    "Lead from where you are.",
    "Today is not a day for being reasonable about what you want.",
    "The hardest part is starting. After that, momentum takes over.",
    "Your energy today is a rare resource. Invest it in what counts.",
    "Today you carry the room without trying.",
    "The move feels risky because it matters. Make it.",
    "What others are waiting for — you're ready for today.",
    "Your authority today is real. Use it wisely.",
    "Today's boldness becomes tomorrow's story.",
    "Don't overthink what your gut has already decided.",
    "The initiative you take today opens the door for next week.",
    "Your timing is right even when it doesn't feel that way.",
    "Today you are the most capable person in your own story.",
    "The action you've been circling — take it.",
    "Today your confidence is a compass, not a costume.",
    "What you put into motion today keeps moving.",
    "The world responds to certainty. Bring it today.",
    "Don't let someone else make the move you were supposed to make.",
    "Today is the day the delay ends.",
    "Your energy today opens things. Use it.",
    "The decision you keep reconsidering — decide today.",
    "Today is not a rehearsal.",
    "What you initiate today has legs. It will run.",
    "Be the one who moves first today.",
    "The answer is yes. Ask the question.",
  ],

  // ── Daily 2 — Moon day ────────────────────────────────────────────────────
  // Emotion, creativity, connection, intuition, sensitivity
  2: [
    "Your emotional read today is more accurate than any logic.",
    "Today is made for depth, not speed.",
    "The person you've been meaning to reach out to — do it today.",
    "What you feel right now is information. Don't ignore it.",
    "Today the right answer arrives through feeling, not thinking.",
    "Creativity is the currency today. Spend it.",
    "Your sensitivity today is a strength, not a liability.",
    "The conversation that needs to happen — today it can.",
    "Today is for the people, not the plan.",
    "What you create today carries unusual depth.",
    "Listen more than you speak today. Something important is being said.",
    "Your intuition has been right before. Trust it again today.",
    "Today is soft, deep, and real. Match its energy.",
    "The connection you invest in today lasts longer than you think.",
    "Don't rush the feeling. Let it land.",
    "Your compassion today is your superpower.",
    "Today is not a day for cold logic. It's a day for genuine presence.",
    "The creative idea circling you — let it out today.",
    "What you express honestly today is received fully.",
    "Today your emotional intelligence earns real results.",
    "The gentle approach works better today than the direct one.",
    "Your mood today is an instrument. Play it well.",
    "Today the heart knows before the mind catches up.",
    "The relationship worth investing in — invest today.",
    "Your feelings are data. Today they're accurate data.",
    "Something beautiful can be created today if you allow it.",
    "Today is for what matters most, not what's most urgent.",
    "The conversation you keep avoiding — it goes better today.",
    "Your empathy today opens doors logic can't.",
    "Don't dismiss the quiet knowing you have right now.",
    "Today is the day the right words come naturally.",
    "What you make with feeling today endures.",
    "The people in your life feel your attention more today.",
    "Today your presence is the gift.",
    "Don't make a financial decision from today's emotional state.",
    "Let yourself feel what you actually feel today.",
    "The creative project waiting for the right mood — this is it.",
    "Today your instincts about people are running at full accuracy.",
    "The kind thing and the right thing are the same today.",
    "What you nurture today grows.",
    "Today is for depth over breadth.",
    "Your emotional attunement today is extraordinary. Use it.",
    "The art, the music, the writing — today they want to happen.",
    "What you feel deeply today deserves to be expressed.",
    "Today connection is more valuable than transaction.",
    "Let yourself be moved. It's useful today.",
    "Your care today reaches further than you know.",
    "The dream that keeps returning — pay attention to it.",
    "Today you understand people better than usual.",
    "What's tender today is also true.",
    "Don't harden today. The softness is working.",
    "Your patience with someone today changes something.",
    "Today is not for pushing. It's for receiving.",
    "The creative instinct you're second-guessing — trust it today.",
    "What you invest emotionally today returns with interest.",
    "Today the right mood produces the right work.",
    "Your attunement today is a rare tool. Use it gently.",
    "Don't make permanent decisions from temporary feelings — but do feel them.",
    "Today the emotional current is running strong. Swim with it.",
    "The quiet observation you make today turns out to be right.",
    "What you feel in your gut about this person — it's accurate.",
    "Today your creativity is alive. Feed it something.",
    "The conversation that needs tenderness — today you have it.",
    "Don't perform today. Be present instead.",
    "Your instinct today is a full sentence. Don't ignore the punctuation.",
    "What you make today with genuine feeling outlasts what you make with effort.",
    "Today the moon is in your corner. Work with it.",
    "The relationship moment you didn't plan — those are the real ones.",
    "Today your emotional depth is an asset in professional settings too.",
    "Let the feeling guide the decision today.",
    "The softness you bring today isn't weakness — it's precision.",
    "Today is for creating, connecting, and going deep.",
    "What matters most to you — give it attention today.",
    "Your sensitivity today picks up things others miss entirely.",
    "Today the right thing and the feeling thing are the same thing.",
    "The creative block lifts today. Move before it returns.",
    "Don't rationalize the intuition. Act on it.",
    "Today you are capable of genuine connection. Don't waste it on surface.",
    "What you feel clearly today, you see clearly tomorrow.",
    "The check-in that costs nothing but changes everything — do it today.",
    "Today is a good day to say the true thing.",
    "Your emotional clarity today is a compass. Follow it.",
    "What you give emotionally today comes back.",
    "Today depth beats speed. Every time.",
    "The dream, the vision, the feeling — today they want to be real.",
    "Your empathy today is working at an unusually high level.",
    "Let today be soft where it needs to be.",
    "The thing you've been feeling but not saying — today it can be said.",
    "Today your creativity and your emotion are speaking the same language.",
    "What you feel right now is trying to tell you something true.",
    "Today the art of listening is more powerful than the art of speaking.",
    "Don't override the feeling with the plan today.",
    "What you create from a real place today is what gets remembered.",
    "Your presence is what's needed today, more than your performance.",
    "The gentleness you show today costs you nothing and gives everything.",
    "Today your inner world is worth paying attention to.",
    "The emotion isn't the problem — it's the signal.",
    "Today is for depth, presence, and genuine human contact.",
    "What you feel today is worth honoring.",
  ],

  // ── Daily 3 — Jupiter day ─────────────────────────────────────────────────
  // Wisdom, planning, sound judgment, ethics, clarity
  3: [
    "Today your judgment is your greatest asset. Trust it.",
    "The right decision is clearer today than it will be tomorrow.",
    "Wisdom over speed — today the careful choice wins.",
    "What you plan today is what actually gets built.",
    "Today is for thinking before doing. The extra moment is worth it.",
    "Your ethical clarity today is a competitive advantage.",
    "The advice you give today lands deeper than usual.",
    "Today is for the long game, not the quick win.",
    "What you understand clearly today — write it down.",
    "The principle that guides you is especially sharp today.",
    "Today patience is not delay — it is strategy.",
    "Your knowledge today is worth more than it usually is.",
    "The right course is visible today. Follow it without shortcuts.",
    "Today is a day for sound decisions that hold up over time.",
    "What you teach today, someone actually learns.",
    "Your perspective today is worth sharing.",
    "The plan that seemed unclear yesterday — today it makes sense.",
    "Today's clarity is a temporary gift. Act on it now.",
    "Integrity today produces results that shortcuts never could.",
    "What you think through carefully today saves you work later.",
    "Today is the best day this week to make an important decision.",
    "Your judgment today cuts through complexity.",
    "The long view is available to you today. Take it.",
    "Today is for counsel, clarity, and sound thinking.",
    "What you refuse to compromise on today protects you later.",
    "Your wisdom today is trustworthy. Use it and share it.",
    "The ethical path and the smart path are the same today.",
    "Today is for thinking, not reacting.",
    "What you understand deeply today becomes the foundation.",
    "Your values guide you well today. Stay close to them.",
    "The deliberate choice beats the fast one today.",
    "Today your ability to see clearly is a gift — use it for big things.",
    "The lesson you've been learning — today it clicks.",
    "What you plan with care today runs smoothly later.",
    "Today is for the decision that required wisdom, not courage.",
    "Your perspective today adds real value. Share it.",
    "The right action is visible today. It was obscured before.",
    "Today is a good day to seek knowledge and give it.",
    "What you think through today, you don't have to redo.",
    "Your moral clarity today is sharp. Lead with it.",
    "Today is a day where careful beats fast every time.",
    "The judgment call you've been avoiding — make it today.",
    "What you invest in understanding today pays back compounded.",
    "Today your sense of right and wrong is trustworthy. Follow it.",
    "The complex problem becomes simpler today. Work it.",
    "Your mind is at its clearest. Use it for what matters.",
    "Today wisdom is the strategy.",
    "What you commit to with integrity today holds.",
    "The plan needs one more look — give it today.",
    "Your clarity today is worth more than someone else's enthusiasm.",
    "Today is for the wise choice, not the exciting one.",
    "What you know deeply — share it today without holding back.",
    "The decision you make today with full awareness is the right one.",
    "Today your foresight is running ahead of everyone else's.",
    "The lesson in the difficulty — you can see it clearly today.",
    "What you do with ethical grounding today lasts.",
    "Today is for depth of thinking, not speed of execution.",
    "Your insight today changes the outcome if you act on it.",
    "The principle you stand on today is worth standing on.",
    "What you reason through today, you won't need to revisit.",
    "Today is a day for getting things right, not just getting them done.",
    "Your judgment today is one of your best assets. Use it for big things.",
    "The thoughtful response beats the fast one today.",
    "What you discern today protects you from what you can't see yet.",
    "Today clarity is power.",
    "The sound decision made today echoes into next month.",
    "Your ethical instinct today is sharp. Trust it completely.",
    "Today is for the deep work that produces lasting results.",
    "What you commit to carefully today you'll be glad you committed to.",
    "The right answer is available today — take the time to find it.",
    "Your wisdom today is the most valuable thing in the room.",
    "Today is for building things that last.",
    "What you think through now saves you something real later.",
    "The advice that needs wisdom — you have it today.",
    "Today your judgment operates above its usual level.",
    "The shortcut you're considering — the long way works better today.",
    "What you know today is worth acting on.",
    "Today is for doing things properly.",
    "Your discernment today is running at full capacity.",
    "The question that needs answering — today you can answer it.",
    "What you get right today sets the standard.",
    "Today is for the considered choice.",
    "Your perspective today carries unusual weight. Use it.",
    "The careful approach today outperforms the bold one.",
    "What you understand today, you can explain to others.",
    "Today is a day where wisdom wins.",
    "Your foresight today is a genuine competitive advantage.",
    "The plan is good. Today you can see why.",
    "What you build on solid ground today doesn't need to be rebuilt.",
    "Today clarity of thought is your most powerful tool.",
    "The right course is visible today. Follow it.",
    "What you examine carefully today you won't regret.",
    "Today your ethics and your intelligence are working together.",
    "The decision that requires wisdom — today you have it.",
    "What you reason through today, you can stand behind.",
    "Today is for doing it right the first time.",
    "Your judgment today is a gift. Apply it where it matters most.",
    "The big picture is clear today. Plan from it.",
    "What you get right today stays right.",
  ],

  // ── Daily 4 — Rahu day ────────────────────────────────────────────────────
  // Research, disruption, unconventional, instability, investigation
  4: [
    "The angle no one else is looking at — look there today.",
    "What seems certain today probably isn't. Verify.",
    "The unconventional path is open today. It might be the right one.",
    "Today is for digging deeper, not moving faster.",
    "The thing that doesn't add up — investigate it today.",
    "What disrupts today's plan might be the better plan.",
    "Today your research ability is sharper than usual.",
    "Don't commit to anything financial today without double checking.",
    "The original idea, the unusual angle — that's today's gift.",
    "What everyone assumes is true — question it today.",
    "Today is for finding what's hidden, not acting on what's visible.",
    "The disruption isn't the problem. It's the redirect.",
    "Don't trust the obvious today. Look behind it.",
    "Your research today uncovers something worth knowing.",
    "Today the unconventional approach solves what conventional can't.",
    "What's been hidden comes to light today if you look.",
    "Don't make the impulsive decision. Sleep on it one night.",
    "Today is for understanding, not executing.",
    "The pattern you've been noticing — today it makes sense.",
    "Your instinct for what's off today is reliable. Trust it.",
    "Don't sign, commit, or transfer anything significant today without verifying.",
    "The unusual solution is the right solution today.",
    "Today is for the questions no one else is asking.",
    "What's been obscured becomes clear today.",
    "The research phase is not wasted time today — it's the work.",
    "Don't assume. Ask. Verify. Check again.",
    "Today your ability to see beneath the surface is working well.",
    "The unexpected development today is pointing somewhere useful.",
    "Today is for exploring, not deciding.",
    "What you discover today changes what you do next week.",
    "The information you find today is more valuable than you initially think.",
    "Don't rush to resolution today. Let things unfold.",
    "Today disruption is a teacher. Listen to what it's saying.",
    "The unconventional route saves time today.",
    "What you investigate today produces clarity by the end of the week.",
    "Today is not for committing. It's for understanding.",
    "The original approach outperforms the standard one today.",
    "Don't let urgency override verification today.",
    "Today the research is the strategy.",
    "What seems like an obstacle today is actually a reroute.",
    "Your curiosity today leads somewhere real.",
    "The thing everyone ignores — that's where the answer is today.",
    "Today is for looking at what's actually there, not what you expect.",
    "The instability today is temporary. Don't build on it.",
    "What you find today by digging was hidden for a reason — and it's useful.",
    "Don't let the chaos of today create permanent decisions.",
    "Today your original thinking is your edge.",
    "The question is more valuable than the answer today.",
    "What breaks today needed to break.",
    "Today is for the investigation, not the verdict.",
    "Your unconventional read today is probably more accurate.",
    "Don't commit financially today. This is the week's highest risk window.",
    "What seems solid today — test it before trusting it.",
    "Today the weird idea is worth entertaining.",
    "The disruption is telling you something. Decode it before reacting.",
    "Today your research changes the story.",
    "Don't move on assumptions today. Move on verified facts.",
    "The original path forward appears today if you're looking.",
    "What you uncover today becomes important next month.",
    "Today is for understanding what's really happening.",
    "The surface explanation is incomplete today. Look deeper.",
    "Don't mistake urgency for importance today.",
    "Your ability to see what others miss is heightened today.",
    "Today is not for speed. It's for accuracy.",
    "What's unusual today is also what's useful.",
    "The standard answer doesn't work today. Try the unusual one.",
    "Today your curiosity is a compass. Follow it.",
    "Don't let the excitement of an idea override the need to verify it.",
    "What you research today saves you from a mistake next week.",
    "Today is for the questions, not the answers.",
    "The unexpected direction today leads somewhere worth going.",
    "Don't sign anything today without reading what you didn't read before.",
    "Your instinct that something is off — it's probably right.",
    "Today the investigation is more valuable than the result.",
    "What disrupts your plan today is trying to improve it.",
    "The pattern that doesn't fit — today you figure out why.",
    "Don't make the confident decision on a Rahu day. Verify first.",
    "Today your original thinking outperforms conventional wisdom.",
    "What you find today in the details changes the big picture.",
    "The unusual approach is the right approach today.",
    "Today is not for closing. It's for discovering.",
    "Your research today is some of your best work.",
    "The thing that seemed random — today it connects.",
    "Don't let the chaos fool you into inaction. The direction is there.",
    "Today is for understanding what's really beneath the surface.",
    "What you verify today prevents a problem you couldn't see coming.",
    "The unconventional angle today is the accurate one.",
    "Don't trust the easy answer today. The real answer takes a little longer.",
    "Your ability to dig today produces gold.",
    "Today the disruption is directional. Find out where it's pointing.",
    "What breaks today makes space for something better.",
    "Don't let today's instability become today's bad decision.",
    "The original solution is available today. Look for it.",
    "Today your skepticism is a useful tool.",
    "What you question today saves you from assuming wrongly.",
    "Today is for the research, the discovery, the unconventional path.",
    "The standard approach misses something today. Deviate slightly.",
    "What you uncover today was always there. You just needed today to see it.",
  ],

  // ── Daily 5 — Mercury day ─────────────────────────────────────────────────
  // Commerce, intelligence, communication, finance, negotiation
  5: [
    "Your commercial instinct today is running at full capacity.",
    "Today is the best day this week to make a financial move.",
    "The negotiation goes in your favor today.",
    "What you communicate clearly today lands completely.",
    "Today your intelligence is your income.",
    "The deal that seemed stuck — today it moves.",
    "Your financial instinct today is sharper than usual. Trust it.",
    "Today is for conversations that matter.",
    "What you pitch today gets heard differently.",
    "The business decision you've been weighing — make it today.",
    "Today your ability to read people is at its peak.",
    "The financial opportunity in front of you — act on it today.",
    "What you negotiate today, you win.",
    "Today your words carry commercial weight.",
    "The sharp idea you had — put a number on it today.",
    "Today is for closing, not deliberating.",
    "Your communication today produces real outcomes.",
    "The money conversation you've been avoiding — have it today.",
    "Today your mind works faster and more accurately than usual.",
    "What you ask for today, you have a real chance of receiving.",
    "The financial move that needed the right timing — this is it.",
    "Today your commercial intelligence is your biggest asset.",
    "What you say today gets taken seriously.",
    "The deal, the pitch, the proposal — today is the right day.",
    "Your analysis today is accurate. Act on it.",
    "Today is for smart financial decisions, not emotional ones.",
    "What you price today is what you get paid.",
    "The business instinct you have right now is trustworthy.",
    "Today your negotiation is your edge.",
    "What you communicate precisely today converts.",
    "The financial window is open today. Step through it.",
    "Your commercial awareness today is heightened.",
    "Today is the day to ask for what you're worth.",
    "The numbers make sense today. Read them and move.",
    "What you sell today gets bought.",
    "Today your intelligence converts into income.",
    "The financial conversation that needed courage — today you have it.",
    "What you write, pitch, or present today performs well.",
    "Today is for the smart money move.",
    "Your instinct for what will sell is running hot today.",
    "The business problem has a solution today. Find it.",
    "What you negotiate precisely today holds up.",
    "Today is the right day to discuss money.",
    "Your commercial clarity today is a real advantage.",
    "The contract, the deal, the agreement — today is the right time.",
    "What you calculate today is accurate.",
    "Today is for the business conversation you've been putting off.",
    "Your reading of the market today is correct.",
    "The financial opportunity you almost missed — today you see it.",
    "What you close today stays closed.",
    "Today your mind and your money are speaking the same language.",
    "The pitch is ready. Today it lands.",
    "What you invoice today, you collect.",
    "Today is for the smart financial move, not the safe one.",
    "Your ability to find the right words today is at its best.",
    "The number you've been afraid to say — say it today.",
    "What you communicate with precision today is understood completely.",
    "Today your commercial instinct is ahead of the market.",
    "The financial conversation goes better today than any other day this week.",
    "What you analyze today provides real clarity.",
    "Today is for making money, not just planning to.",
    "Your intelligence today is a tool. Use it commercially.",
    "The offer, the ask, the proposal — today it works.",
    "What you negotiate with confidence today holds.",
    "Today your words and numbers are both working for you.",
    "The business move that required confidence — today you have it.",
    "What you price accurately today earns accurately.",
    "Today is the day to have the money conversation.",
    "Your financial instinct is the most reliable it has been all week.",
    "The deal you thought was dead — approach it today.",
    "What you present today is received at full value.",
    "Today your communication is your revenue.",
    "The smart financial decision is visible today. Make it.",
    "What you close today with confidence stays closed.",
    "Today is for converting intelligence into income.",
    "Your commercial awareness today is running above average.",
    "The business problem is solvable today. Engage with it.",
    "What you pitch clearly today converts at a higher rate.",
    "Today is the right day for any money-related conversation.",
    "Your negotiation instinct is trustworthy today.",
    "The financial clarity you needed — it arrives today.",
    "What you do commercially today produces results this week.",
    "Today your mind is at its fastest and most accurate.",
    "The contract needs to be signed today, not tomorrow.",
    "What you communicate with precision today, people act on.",
    "Today financial intelligence is your edge.",
    "The move that required financial confidence — make it today.",
    "What you sell, pitch, or negotiate today wins.",
    "Today is the best day this week to discuss money.",
    "Your commercial instinct today is not to be ignored.",
    "The business decision you keep postponing — today is the day.",
    "What you ask for today with confidence, you receive.",
    "Today your words build income. Use them precisely.",
    "The financial window is wider today than it has been.",
    "What you invest attention in commercially today pays back.",
    "Today is for the numbers, the deal, the smart money move.",
    "Your intelligence today earns.",
    "The conversation that needed to happen about money — have it today.",
    "What you close today with clarity stays.",
  ],

  // ── Daily 6 — Venus day ───────────────────────────────────────────────────
  // Beauty, harmony, relationships, creativity, warmth, expression
  6: [
    "Beauty is not a distraction today — it's the direction.",
    "What you create today carries unusual warmth.",
    "The relationship worth investing in — invest today.",
    "Today is for warmth, art, and genuine human connection.",
    "What you express from the heart today, people feel.",
    "Today the aesthetic choice is also the correct choice.",
    "The creative work waiting for the right day — this is that day.",
    "What you make beautiful today lasts longer than what you make efficient.",
    "Today is for the people who deserve your full attention.",
    "Your warmth today opens doors that strategy can't.",
    "The creative project has been waiting for today.",
    "What you say with care today changes something.",
    "Today is for making the world slightly more beautiful.",
    "Your sense of beauty today is a reliable guide.",
    "The relationship moment you didn't plan is the real one.",
    "Today warmth is more powerful than intelligence.",
    "What you appreciate today, you keep.",
    "Today is for creating, not just producing.",
    "Your taste today is exactly right. Trust it.",
    "The person who deserves acknowledgment — acknowledge them today.",
    "Today your creative expression is at its peak.",
    "What you invest in beauty today returns in ways you don't expect.",
    "Today is for the genuine, the warm, the beautiful.",
    "Your aesthetic choices today are unusually sound.",
    "The creative idea you've been sitting on — today it's ready.",
    "What you make with love today endures.",
    "Today relationships take priority over tasks.",
    "Your warmth today is your most effective tool.",
    "The beautiful solution is the right solution today.",
    "What you create from genuine feeling today resonates.",
    "Today is for connection, not transaction.",
    "Your sense of what's beautiful and what's right aligns today.",
    "The creative work you put off — today do it.",
    "What you express authentically today is received fully.",
    "Today is a good day to tell someone they matter.",
    "Your creativity today is running at its most expressive.",
    "The relationship investment today has compounding returns.",
    "What you do with genuine care today stands out.",
    "Today beauty and practicality are the same thing.",
    "Your warmth today produces results that strategy couldn't.",
    "The creative expression you've been holding back — release it today.",
    "What you make today from a real place gets remembered.",
    "Today is for the human moment, not the efficient one.",
    "Your sense of harmony today makes you the best person in the room.",
    "The art, the writing, the design — today they want to happen.",
    "What you appreciate deeply today you don't lose.",
    "Today is for depth over efficiency.",
    "Your care for quality today produces something worth having.",
    "The environment, the space, the aesthetic — today it matters.",
    "What you express with genuine feeling today can't be faked.",
    "Today is for creating what you actually want to create.",
    "Your creative instinct today is your most accurate compass.",
    "The relationship that deserves more — give it more today.",
    "What you make beautiful today becomes a standard.",
    "Today is for warmth, presence, and genuine expression.",
    "Your appreciation today is worth voicing.",
    "The creative block lifts today. Move before it returns.",
    "What you invest in beauty today pays back in ways you didn't calculate.",
    "Today the elegant solution beats the forceful one.",
    "Your eye for what's right today is trustworthy.",
    "The gentle approach works better today than the direct one.",
    "What you create with care today earns respect that speed can't.",
    "Today is for the people you love and the work you love.",
    "Your warmth today is felt at an unusually deep level.",
    "The creative work is not separate from the real work today.",
    "What you express genuinely today lands completely.",
    "Today is a good day to make something beautiful.",
    "Your sense of what's harmonious today guides good decisions.",
    "The relationship moment — don't let it pass today.",
    "What you appreciate today, you nurture.",
    "Today is for quality over quantity in everything.",
    "Your creativity today is alive. Feed it.",
    "The warm response is also the effective response today.",
    "What you make today with genuine intention outlasts what you make in a hurry.",
    "Today beauty is a strategy.",
    "Your aesthetic sense today is an asset.",
    "The person who needed to hear something kind — say it today.",
    "What you invest in creatively today grows.",
    "Today is for the beautiful, the warm, and the genuinely expressed.",
    "Your warmth today changes how people feel about working with you.",
    "The creative decision is also the right decision today.",
    "What you create from a real place today resonates long after.",
    "Today is not for rushing. It's for getting it beautiful.",
    "Your sense of harmony today resolves what analysis couldn't.",
    "The relationship worth having — be present in it today.",
    "What you do with genuine care today is noticed.",
    "Today is for expression, connection, and creation.",
    "Your warmth today is a form of leadership.",
    "The creative work you love — give it today's energy.",
    "What you make today with full presence becomes something worth keeping.",
    "Today beauty is not the opposite of productivity.",
    "Your creative expression today finds its natural form.",
    "The kind thing today is also the wise thing.",
    "What you appreciate about someone — tell them today.",
    "Today is for warmth and creativity in equal measure.",
    "Your sense of beauty today is a reliable guide to the right choice.",
    "The creative project needs today's energy. Give it.",
    "What you invest in relationships today compounds quietly.",
    "Today is for the genuine, the warm, and the beautiful.",
  ],

  // ── Daily 7 — Ketu day ────────────────────────────────────────────────────
  // Fortune, intuition, spiritual depth, luck, seeking
  7: [
    "Something is working in your favor today that you can't see yet.",
    "Trust the instinct. Today it's running ahead of the explanation.",
    "The lucky thing today arrives when you stop chasing it.",
    "Your intuition today is more reliable than your analysis.",
    "Today fortune is quiet. That doesn't mean it isn't there.",
    "The unexpected development today is pointed in a good direction.",
    "Don't force the outcome today. Let it come.",
    "Your gut feeling right now is carrying more information than you know.",
    "Today luck works through the path of least resistance.",
    "The opportunity you didn't plan for — today it might show up.",
    "Trust what you feel before you can explain it today.",
    "Today is a day where things work out better than you expected.",
    "The question you've been sitting with — today an answer arrives.",
    "Your intuition today is operating above its usual accuracy.",
    "Don't overthink the fortunate thing that's trying to arrive.",
    "Today luck is structural. You don't have to make it happen.",
    "The philosophical question that's been occupying you — clarity comes today.",
    "Your instinct about this person today is accurate.",
    "Today is for deep thinking and trusting what surfaces.",
    "Something good is moving toward you. Let it arrive.",
    "The decision that needed more information — today you have enough.",
    "Your read on this situation today is correct.",
    "Today fortune rewards the person who stays open.",
    "Don't dismiss the unusual thought that arrives today.",
    "The path forward becomes clearer today without effort.",
    "Your instinct is ahead of your logic today. Go with it.",
    "Today is for allowing, not forcing.",
    "The unexpected connection today leads somewhere real.",
    "Your depth today is visible to the right people.",
    "Today what's meant to arrive, arrives.",
    "Trust the hunch. Today hunches are worth something.",
    "The coincidence today is probably not a coincidence.",
    "Your philosophical clarity today provides real practical guidance.",
    "Today is for going deep, not wide.",
    "Something that's been stuck quietly unsticks today.",
    "Your sense of what's right today is trustworthy at a deeper level.",
    "Today the lucky thing comes through the unexpected channel.",
    "Don't plan today's fortune — receive it.",
    "Your intuition today is running at full accuracy.",
    "The quiet knowing you have right now is correct.",
    "Today is for depth, reflection, and following the instinct.",
    "Something that seemed random today reveals itself as intentional.",
    "Your read on this is right. Trust it.",
    "Today fortune is available. Stay open to how it arrives.",
    "The deeper question has an answer today.",
    "Your instinct about the next move is correct today.",
    "Today is not for forcing. It's for receiving.",
    "The thing you almost dismissed today is worth a second look.",
    "Your depth today produces insight that speed can't manufacture.",
    "Today luck moves through intuition, not effort.",
    "The meaningful coincidence today is pointing somewhere.",
    "Your philosophical sense today provides real practical clarity.",
    "Today something works out that you had given up on.",
    "Trust the quiet certainty you have right now.",
    "Today the fortunate outcome arrives through the unconventional path.",
    "Your instinct today is running several steps ahead.",
    "The unexpected development today is good news, not bad.",
    "Today is for following the thread wherever it leads.",
    "Your depth of perception today is unusually high.",
    "The hunch that won't leave you alone — it's right.",
    "Today fortune doesn't announce itself. Watch for it quietly.",
    "Your intuition today is the most accurate tool you have.",
    "Something is shifting in your favor today.",
    "Today the right door opens when you stop pushing the wrong one.",
    "Your sense of what's true today is reliable.",
    "The path forward shows itself today if you're patient.",
    "Today depth beats speed at every turn.",
    "Your quiet awareness today picks up things logic misses.",
    "The unexpected good thing today — let it be good.",
    "Today your instinct is two steps ahead of your reasoning.",
    "Something small today carries large meaning.",
    "Your depth of understanding today produces real clarity.",
    "Today fortune moves through the path you haven't planned.",
    "The philosophical insight today has practical application.",
    "Your feeling about this is right. Trust it more than the analysis.",
    "Today is for staying open to what isn't yet visible.",
    "Something that's been uncertain becomes clear today.",
    "Your intuition is your most reliable instrument today.",
    "Today the lucky break comes in disguise.",
    "Don't overthink the opportunity that's presenting itself.",
    "Your depth today is your edge.",
    "The coincidence today is worth following.",
    "Today what you need arrives before you ask for it.",
    "Your instinct about the right direction is sound today.",
    "Today is for trusting the process even when you can't see the outcome.",
    "Something is working for you behind the scenes today.",
    "Your quiet knowing today is worth more than loud certainty.",
    "The unexpected path today leads somewhere better.",
    "Today fortune is quiet, real, and available.",
    "Your intuition today is carrying more information than usual.",
    "The answer you've been seeking — today it surfaces.",
    "Today is for depth, instinct, and allowing the fortunate thing.",
    "Your sense of the right move today is correct.",
    "Something that seemed lost comes back today.",
    "Today luck rewards the person who stays present.",
    "Your philosophical clarity today is not separate from practical wisdom.",
    "The deep knowing you have right now — act on it.",
    "Today fortune doesn't require effort. It requires openness.",
    "Your instinct today sees what analysis can't.",
    "Something today arrives at exactly the right time.",
  ],

  // ── Daily 8 — Saturn day ──────────────────────────────────────────────────
  // Karma, discipline, sustained effort, integrity, patience
  8: [
    "What you build today with real effort outlasts everything built fast.",
    "Today discipline is not the obstacle. It's the reward.",
    "The shortcut you're considering will cost more than the long way.",
    "Today's work is tomorrow's foundation. Don't rush it.",
    "What you do with integrity today compounds.",
    "The effort that feels invisible today is actually the most visible thing.",
    "Today patience is not passive. It's active and precise.",
    "What you complete today you won't have to redo.",
    "Today the difficult thing done properly is worth ten easy things done quickly.",
    "Your discipline today is your most powerful asset.",
    "The work that requires sustained attention — today you can give it.",
    "What you build carefully today holds.",
    "Today is not for shortcuts. It's for doing it right.",
    "Your effort today is a form of investment.",
    "The boring consistent thing today produces the extraordinary result next month.",
    "What you refuse to compromise on today protects you later.",
    "Today your follow-through matters more than your start.",
    "The long-term decision made with integrity today holds up in any weather.",
    "What you do today that no one notices becomes what everyone depends on.",
    "Today effort is the strategy.",
    "Your patience today is not delay — it's precision.",
    "The unglamorous work today is the most important work.",
    "What you finish today you don't carry into next week.",
    "Today is for the real work, not the visible work.",
    "Your discipline today produces results that enthusiasm alone never could.",
    "The thing that requires sustained focus — today you have it.",
    "What you do with full integrity today earns trust that shortcuts can't buy.",
    "Today is for completing, not starting.",
    "Your consistency today is a competitive advantage.",
    "The hard thing done right today is worth more than ten easy things.",
    "What you put real effort into today stays.",
    "Today is not for announcing. It's for doing.",
    "Your patience is running at full capacity today.",
    "The foundation you lay today determines what can be built later.",
    "What you do thoroughly today saves you work next month.",
    "Today your persistence is the differentiator.",
    "The karma of today's effort is real. Do the real work.",
    "What you earn honestly today is actually yours.",
    "Today is for the work that requires everything and produces something that lasts.",
    "Your discipline today earns what enthusiasm promises.",
    "The result that requires time is being built today. Keep going.",
    "What you do with integrity today doesn't need to be redone.",
    "Today effort compounds. Make it count.",
    "Your follow-through today is the thing that differentiates you.",
    "The slow path today is the fast path next year.",
    "What you build today that lasts is what today is for.",
    "Today is for the quiet, difficult, unglamorous work that matters most.",
    "Your persistence today is more valuable than your talent.",
    "The difficult choice made with integrity today is the right choice.",
    "What you do carefully today you'll be proud of next month.",
    "Today is not a day for half measures.",
    "Your discipline is your most reliable asset today.",
    "The thing that requires consistent effort — today is one of those days.",
    "What you do with real attention today produces real results.",
    "Today the patient choice wins over the exciting one.",
    "Your integrity today is building something invisible and permanent.",
    "The foundation work is the real work today.",
    "What you complete with full effort today doesn't need to be revisited.",
    "Today is for earning it, not assuming it.",
    "Your patience today is a form of strength.",
    "The work that nobody sees today is the work that matters most.",
    "What you do right today competes at a higher level tomorrow.",
    "Today effort is not the cost — it's the point.",
    "Your discipline today is visible to the right people even when it feels unseen.",
    "The difficult thing today is also the important thing.",
    "What you build with real integrity today is yours to keep.",
    "Today is for doing the hard thing properly.",
    "Your patience today opens what urgency would have closed.",
    "The sustained effort today produces what the burst of energy never could.",
    "What you refuse to shortcut today is what succeeds.",
    "Today is for showing up fully, not just showing up.",
    "Your follow-through today is worth more than your ideas.",
    "The karma of doing it right today — it's real.",
    "What you put real effort into today doesn't need to be done again.",
    "Today discipline wins over inspiration.",
    "Your patience is running at its most powerful today.",
    "The consistent thing done today is what builds the extraordinary outcome.",
    "What you earn with real effort today, you keep.",
    "Today is for the work that requires your full capacity.",
    "Your persistence today outperforms everyone who gave up yesterday.",
    "The long way today is the right way.",
    "What you complete with integrity today holds under pressure.",
    "Today effort is the answer, not the question.",
    "Your discipline today earns what shortcuts only promise.",
    "The boring consistent work today produces the exciting result later.",
    "What you do with sustained attention today changes something.",
    "Today is for building, not announcing.",
    "Your patience is your biggest competitive advantage today.",
    "The effort today feels invisible but it's compounding.",
    "What you do right today you won't redo tomorrow.",
    "Today is for the real work.",
    "Your follow-through is your most valuable quality today.",
    "The foundation laid today determines what the future can support.",
    "What you build with real integrity today is not easily taken.",
    "Today is for earning, not hoping.",
    "Your discipline today is building something that lasts.",
    "The work that no one applauds today is the work that matters.",
    "What you complete today with full attention stays complete.",
    "Today patience is power.",
  ],

  // ── Daily 9 — Mars day ────────────────────────────────────────────────────
  // Energy, courage, action, passion, competition, physicality
  9: [
    "The energy today is real. Direct it before it directs you.",
    "Today courage is not optional — it's available. Use it.",
    "What you pursue with full intensity today, you catch.",
    "The physical outlet is not optional today — find one.",
    "Today is the day to do the thing that requires nerve.",
    "Your energy today is a resource. Don't leave it unused.",
    "The competition — today you're ready for it.",
    "What you fight for today, you have a real chance of winning.",
    "Today is for the bold move, not the careful one.",
    "Your courage today is at its most accessible.",
    "The thing that requires physical effort — today is the right day.",
    "What you pursue with passion today gets traction.",
    "Today the aggressive approach works better than the patient one.",
    "Your intensity today is an asset. Channel it deliberately.",
    "The confrontation that needs happening — today you have the nerve for it.",
    "What you commit to with full energy today moves.",
    "Today is for action, not analysis.",
    "Your competitive instinct today is your edge.",
    "The challenge in front of you — today you have what it takes.",
    "What you go after with everything today, you reach.",
    "Today energy is the currency. Spend it on what matters.",
    "Your boldness today produces results that caution never could.",
    "The physical work, the intense effort — today it's available.",
    "What you fight for today with genuine conviction wins.",
    "Today is not for hesitation. It's for movement.",
    "Your courage today is not recklessness — it's readiness.",
    "The hardest thing on the list today — start with that.",
    "What you go for fully today gets a real response.",
    "Today is the right day to confront what you've been avoiding.",
    "Your energy today can move things that have been stuck.",
    "The competitive situation today — you are genuinely ready.",
    "What you pursue with clarity and intensity today converts.",
    "Today the direct approach beats the strategic one.",
    "Your physical energy today is a tool. Put it to use.",
    "The bold ask today gets the bold answer.",
    "What you defend today with real conviction, you keep.",
    "Today intensity and focus together produce extraordinary results.",
    "Your courage today is fully charged.",
    "The thing that required guts — today you have them.",
    "What you pursue with everything today reaches further.",
    "Today is for the action you've been building toward.",
    "Your competitive edge today is real. Use it.",
    "The obstacle today is smaller than your energy. Push through.",
    "What you fight for today with clarity, you win.",
    "Today is not for playing safe.",
    "Your energy today is too valuable to waste on small things.",
    "The challenge today is sized for exactly who you are right now.",
    "What you pursue today with full commitment, moves.",
    "Today is for the physical, the passionate, and the brave.",
    "Your boldness today is backed by the chart.",
    "The fight worth having — today you have the energy for it.",
    "What you go after with intensity today changes the trajectory.",
    "Today the direct approach beats patience.",
    "Your competitive instinct is your most accurate tool today.",
    "The hardest move today is the right move.",
    "What you pursue with passion today earns respect regardless of outcome.",
    "Today energy without direction is wasted. Pick the target.",
    "Your courage today is not performance — it's real.",
    "The physical outlet today resets everything else.",
    "What you fight for today with genuine care, you fight well.",
    "Today is for going all in on the thing that matters.",
    "Your intensity today is available for deployment. Use it wisely.",
    "The confrontation that needed to happen — today is the time.",
    "What you pursue boldly today produces movement.",
    "Today the aggressive approach works.",
    "Your energy today is one of your best resources this week.",
    "The bold action today produces what caution never could.",
    "What you go for today with everything you have — you have a real shot.",
    "Today is for the challenge, not the comfort zone.",
    "Your competitive fire today is fully lit.",
    "The thing you've been building courage for — today is the day.",
    "What you pursue today with real intensity, stays pursued.",
    "Today energy and clarity together are unstoppable.",
    "Your boldness today changes what's possible.",
    "The physical work, the hard effort, the intense push — today it converts.",
    "What you fight for today with genuine conviction is worth fighting for.",
    "Today is for the move that requires everything you have.",
    "Your courage today opens what patience couldn't.",
    "The intense effort today produces results others can't match.",
    "What you go after fully today has a real chance.",
    "Today is for moving, not planning.",
    "Your energy today can accomplish what took others a week.",
    "The challenge is real. So is your readiness.",
    "What you pursue with passion and clarity today — pursue it completely.",
    "Today the direct, bold, intense approach is the right one.",
    "Your competitive instinct today is running accurately.",
    "The thing that required nerve — today you have it.",
    "What you do with full intensity today can't be easily undone.",
    "Today is for showing what you're capable of.",
    "Your energy today is a rare resource. Don't leave it on the table.",
    "The bold move today is the right move.",
    "What you fight for today with real heart, you fight well.",
    "Today is for action, intensity, and going all in.",
    "Your courage today is the most useful thing you own.",
    "The obstacle in front of you — today your energy is bigger than it.",
    "What you pursue with everything today is what actually moves.",
    "Today intensity is the strategy.",
  ],
};
