// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz0dWTI9qS3dj2it9UYW_rabVTzqrWt-M',
    appId: '1:554790488195:web:d229029aec144923b2b3b6',
    messagingSenderId: '554790488195',
    projectId: 'aastrosphere-mobile',
    authDomain: 'aastrosphere-mobile.firebaseapp.com',
    storageBucket: 'aastrosphere-mobile.firebasestorage.app',
    measurementId: 'G-DDX2MEZX4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuQs_hP3hEIE8YnuBfqnx5Ek8EfzNX2Mo',
    appId: '1:554790488195:android:7e50e4c88ebfd263b2b3b6',
    messagingSenderId: '554790488195',
    projectId: 'aastrosphere-mobile',
    storageBucket: 'aastrosphere-mobile.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXZ5lAA0Iu7bNWFcgl660M8KjDrQ_K7A',
    appId: '1:554790488195:ios:5e2f1a35ae46f2c7b2b3b6',
    messagingSenderId: '554790488195',
    projectId: 'aastrosphere-mobile',
    storageBucket: 'aastrosphere-mobile.firebasestorage.app',
    iosBundleId: 'com.aastrosphere.app',
  );
}
