name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UI Packages ---
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  pinput: ^5.0.0
  google_places_flutter: ^2.0.8 # <-- YEH NAYA ADD HUA HAI (Places API)

  # --- Firebase Packages ---
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5 

  # --- State Management ---
  flutter_riverpod: ^2.5.1 

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # --- Assets ---
  assets:
    - assets/images/wooden_door_texture.png
    - assets/images/zodiac_circle_gold.png